
server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
    include-stacktrace: never
#  ssl:
#    key-store: classpath:springboot.p12
#    key-store-password: shalimar
#    key-store-type: pkcs12
#    key-alias: springboot
#    key-password: shalimar
  port: ${PORT}
spring:
  banner:
    location: classpath:/banner/orphea.txt
  sql:
    init:
      schema-locations: classpath:db/quartz_tables_h2.sql
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:ignite
    password: ''

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: update
    show-sql: false
  #  main:
  #    allow-bean-definition-overriding: true

  quartz:
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate

file:
  upload-dir=/Users/rakeshmalik/orphea/uploads

logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        security: DEBUG
#          web:
#            FilterChainProxy: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    supportedSubmitMethods: ["get", "put", "post", "delete", "options", "head", "patch", "trace"]
    doc-expansion: none
    persistAuthorization: true
    tryItOutEnabled: true
    syntaxHighlight:
      theme: arta
    disable-swagger-default-url: true