apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: bosler-spark-history-server
  name: bosler-spark-history-server
  namespace: {{ .Values.namespace }}
spec:
  replicas: 0
  selector:
    matchLabels:
      name: bosler-spark-history-server
  template:
    metadata:
      labels:
        name: bosler-spark-history-server
    spec:
      containers:
        - name: bosler-spark-history-server
          image: "{{ include "bosler-gke.repo_path" . }}spark-history-server:{{ .Values.versions.sparkHistoryServer }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
    
          command:
            - /usr/bin/tini
            - -s
            - --
            - /opt/spark/bin/spark-class
            # - -Dfs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem
            # - -Dfs.AbstractFileSystem.gs.impl com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS
            - -Dspark.history.fs.logDirectory={{ .Values.backend.hdfsEndpoint }}/bosler/spark-streaming/
            # - -Dgoogle.cloud.auth.service.account.enable=true
            # - -Dgoogle.cloud.auth.service.account.json.keyfile=/opt/spark/conf/google_creds.json
            # - -Dspark.history.fs.logDirectory=s3a://spark-streaming/checkpoint/
            # - -Dspark.hadoop.fs.s3a.endpoint=http://minio:9000
            # - -Dspark.hadoop.fs.s3a.access.key=miniominio
            # - -Dspark.hadoop.fs.s3a.secret.key=miniominio
            - org.apache.spark.deploy.history.HistoryServer

          ports:
            - name: http
              protocol: TCP
              containerPort: 18080

          readinessProbe:
            timeoutSeconds: 4
            httpGet:
              path: /
              port: http

          livenessProbe:
            timeoutSeconds: 4
            httpGet:
              path: /
              port: http

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: bosler-spark-history-server
  name: bosler-spark-history-server
  namespace: {{ .Values.namespace }}
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "bosler-backend-config"}'
spec:
  type: NodePort
  ports:
    - name: bosler-spark-history-server
      port: 18080
      targetPort: 18080
  selector:
    name: bosler-spark-history-server
status:
  loadBalancer: {}
