services:
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    depends_on:
      - snap
      - snap-ui
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl:rw
    ports:
      - 8082:8082

  snap:
    privileged: true
    security_opt:
      - label:disable
      - seccomp:unconfined
    image: snap
    container_name: snap
    build:
      context: ./repos/snap
    # ports:
    #   - "8080:8080"
    environment:
      - ALLOWED_ORIGINS=http://127.0.0.1:5500,http://127.0.0.1:3000,http://localhost:3000,http://localhost:8080,http://localhost:8090,http://snap.orphea.io:8082,https://snap.orphea.io:8082,https://nexus.orphea.io:8082
      - ARTIFACT_STORE=/orphea/snap/artifactory
      - BASE_URL=http://dev.orphea.io:8080
      - DB_HOST=snap-db
      - DB_PASSWORD=solaris
      - DB_PORT=15432
      - DB_USERNAME=postgres
      - SWAGGER_UI=true
      - TOKEN_EXPIRATION=604800000
      - TOKEN_SECRET=MDRjYTAyM2IzOTUxMmU0NmQwYzJjZjRiNDhkjhkjhkjhdasldjalNWFhYzYxZDM0MzAyOTk0Yzg3Ym9zbGVyZWQ0ZWZmMjI1ZGNmM2IwYTIxODczOWYzODk3MDUxYTA1
      - GITHUB_PAT=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
      - LOG_FILE_PATH=/orphea/snap/logs
      - GO_HARBOR_USERNAME=manav
      - GO_HARBOR_PASSWORD=Manav1234
      - GO_HARBOR_URL=snap.orphea.io:7376
      - GO_HARBOR_PROJECT=orphea
    devices:
      - /dev/fuse:/dev/fuse:rw
    volumes:
      - /orphea/snap:/orphea/snap
      - /var/lib/mycontainer:/var/lib/containers:Z
    depends_on:
      - snap-db
    command: [
        "java",
        "-javaagent:/app/elastic-apm-agent-1.52.1.jar",
        "-Delastic.apm.service_name=snap",
        "-Delastic.apm.secret_token=supersecrettoken",
        "-Delastic.apm.server_url=http://fleet-server:8200",
        "-Delastic.apm.environment=production",
        "-Delastic.apm.application_packages=io.orphea",
        "-jar",
        "/app/snap-0.0.1-SNAPSHOT.jar",
      ]
    restart: on-failure
    working_dir: /app

  snap-ui:
    image: snap-ui:latest
    container_name: snap-ui
    build:
      context: ./repos/snap-ui
    depends_on:
      - snap
    restart: on-failure

  snap-db:
    image: postgres:16
    container_name: snap-db
    volumes:
      - /orphea/snap/db/data:/var/lib/postgresql/data
      - /orphea/snap/db/dbscripts/:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=solaris
