apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: bosler-spark
  namespace: bosler

spec:
  type: "Python"
  pythonVersion: "3"
  mode: cluster
  image: "europe-west1-docker.pkg.dev/bosler-bnp/bosler-cr/funnel:latest"
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/6a6983c9-3043-4163-95e8-9afe7707b9b7/mytransform/funnel_datasets.py
  sparkVersion: "3.2.0"
  # hadoopConf:
  #   "fs.s3a.endpoint": "http://minio:9000"
  # sparkConf:
  #   "spark.kubernetes.driver.annotation.sidecar.istio.io/inject": "false"
  #   "spark.kubernetes.executor.annotation.sidecar.istio.io/inject": "false"
  sparkConf:
    spark.eventLog.enabled: "true"
    spark.ui.enabled: "false"
    spark.eventLog.dir: s3a://spark-streaming/checkpoint/
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20

  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    envSecretKeyRefs:
      MINIO_ACCESS_KEY:
        name: bosler-secret
        key: minio-username
      MINIO_SECRET_KEY:
        name: bosler-secret
        key: minio-password
      POSTGRES_USERNAME:
        name: bosler-secret
        key: boson-db-username
      POSTGRES_PASSWORD:
        name: bosler-secret
        key: boson-db-password
    envVars:
      POSTGRES_DATABASE: boson
      POSTGRES_HOST: boson-db
      POSTGRES_PORT: "5432"
      JULIA_URL: "http://boson:58542/"
      MINIO_S3_ENDPOINT: "http://minio:9000"
      REPOSITORY: 6a6983c9-3043-4163-95e8-9afe7707b9b7
      BRANCH: master
      USER: 286d69fe-c2dd-410f-95c6-ace3ffeb5b7f
      SCRIPTPATH: mytransform/funnel_datasets.py
    # below not working for some reason so using envVars
    env:
      - name: POSTGRES_DATABASE
        value: boson
      - name: POSTGRES_HOST
        value: boson-db
      - name: POSTGRES_PORT
        value: "5432"
      - name: JULIA_URL
        value: "http://boson:58542/"
      - name: S3_ENDPOINT
        value: "http://minio:9000"
    labels:
      version: 3.2.0
    serviceAccount: spark
  executor:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.2.0
