apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: frontend
  name: frontend
  namespace: orphea
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
        - image: europe-west1-docker.pkg.dev/orphea-bnp/orphea-cr/frontend:latest
          imagePullPolicy: IfNotPresent
          name: frontend
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_BASE_URL
              value: https://bnp.orphea.io
            - name: REACT_APP_BASE_URL_API
              value: https://bnp.orphea.io/api
            - name: REACT_APP_PARLER_URL
              value: ws://parler:8999/
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: frontend
  name: frontend
  namespace: orphea
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "orphea-backend-config"}'
spec:
  type: ClusterIP
  ports:
    - name: frontend
      port: 80
      targetPort: 80
  selector:
    name: frontend
status:
  loadBalancer: {}
