apiVersion: v1
kind: Secret
metadata:
  name: movetodata-secret
  namespace: movetodata
type: Opaque
data:
  boson-db-username: cG9zdGdyZXM=
  boson-db-password: c29sYXJpcw==
  # dockerhub token 6bff1c32-b338-461c-a8d9-2c1f125edd5b
  minio-username: bWluaW9taW5pbw==
  minio-password: bWluaW9taW5pbw==
  fractal-templates-token: Z2hwXzB1VlNhNGwyNkE0ZGQyNzFkeXFqSnprZzMydzY1YTFzUXRkZg==
  jwt-secret: WGJmU1lROHZKMko2VDg4
