apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: orphea-spark-history-server
  name: orphea-spark-history-server
  namespace: orphea
spec:
  replicas: 1
  selector:
    matchLabels:
      name: orphea-spark-history-server
  template:
    metadata:
      labels:
        name: orphea-spark-history-server
    spec:
      containers:
        - name: orphea-spark-history-server
          image: europe-west1-docker.pkg.dev/orphea-bnp/orphea-cr/spark-history-server:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
    
          command:
            - /usr/bin/tini
            - -s
            - --
            - /opt/spark/bin/spark-class
            - -Dspark.history.fs.logDirectory=s3a://spark-streaming/checkpoint/
            - -Dspark.hadoop.fs.s3a.endpoint=http://minio:9000
            - -Dspark.hadoop.fs.s3a.access.key=miniominio
            - -Dspark.hadoop.fs.s3a.secret.key=miniominio
            - org.apache.spark.deploy.history.HistoryServer

          ports:
            - name: http
              protocol: TCP
              containerPort: 18080

          readinessProbe:
            timeoutSeconds: 4
            httpGet:
              path: /
              port: http

          livenessProbe:
            timeoutSeconds: 4
            httpGet:
              path: /
              port: http

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: orphea-spark-history-server
  name: orphea-spark-history-server
  namespace: orphea
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "orphea-backend-config"}'
spec:
  type: ClusterIP
  ports:
    - name: orphea-spark-history-server
      port: 18080
      targetPort: 18080
  selector:
    name: orphea-spark-history-server
status:
  loadBalancer: {}
