name: Whitelist Workflow - Dev2

on:
  push:
    paths:
    - 'whitelist.bosler-dev2.txt'

jobs:
  setup-and-deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup - gcloud / gsutil
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.DEV2_GKE_SA_KEY }}
        project_id: ${{ secrets.DEV2_GKE_PROJECT }}
        export_default_credentials: true

    - name: Deploy
      run: |-
        WHITELIST=$(paste -s -d, whitelist.bosler-dev2.txt)
        SECPOLICY="bosler-dev2"
        gcloud compute security-policies rules update 1000 \
          --security-policy "${SECPOLICY}" \
          --description "allow traffic from whitelist.txt" \
          --src-ip-ranges "${WHITELIST}" \
          --action "allow"
