export const ERROR = "error";
export const DEFAULT_CRON_JOB = "0 * * * *";
export const DIVIDER_TEXT = "OR";
export const FRENCH_LOCALE = {
  everyText: "chaque",
  emptyMonths: "mois vides",
  emptyMonthDays: "jours du mois vides",
  emptyMonthDaysShort: "jours vides",
  emptyWeekDays: "jours de la semaine vides",
  emptyWeekDaysShort: "jours vides",
  emptyHours: "heures vides",
  emptyMinutes: "minutes vides",
  emptyMinutesForHourPeriod: "minutes vides",
  yearOption: "année",
  monthOption: "mois",
  weekOption: "semaine",
  dayOption: "jour",
  hourOption: "heure",
  minuteOption: "minute",
  rebootOption: "redémarrage",
  prefixPeriod: "tous les",
  prefixMonths: "les mois",
  prefixMonthDays: "les jours",
  prefixWeekDays: "les jours de la semaine",
  prefixWeekDaysForMonthAndYearPeriod: "les",
  prefixHours: "les heures",
  prefixMinutes: "les minutes",
  prefixMinutesForHourPeriod: "les",
  suffixMinutesForHourPeriod: "minutes",
  errorInvalidCron: "Expression cron invalide",
  clearButtonText: "Effacer",
  weekDays: [
    "Dimanche",
    "Lundi",
    "Mardi",
    "Mercredi",
    "Jeudi",
    "Vendredi",
    "Samedi",
  ],
  months: [
    "Janvier",
    "Février",
    "Mars",
    "Avril",
    "Mai",
    "Juin",
    "Juillet",
    "Août",
    "Septembre",
    "Octobre",
    "Novembre",
    "Décembre",
  ],
  altWeekDays: ["Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam"],
  altMonths: [
    "Janv",
    "Fév",
    "Mars",
    "Avr",
    "Mai",
    "Juin",
    "Juil",
    "Août",
    "Sept",
    "Oct",
    "Nov",
    "Déc",
  ],
};
