filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config:
        type: container
        paths:
          - /var/lib/docker/containers/${data.container.id}/*.log

    - type: kubernetes
      node: ${NODE_NAME}
      hints.enabled: true
      templates:
        - condition:
            equals:
              kubernetes.namespace: "default"
          config:
            - type: container
              paths:
                - /var/log/containers/*${data.kubernetes.container.id}.log

filebeat.inputs:
- type: filestream
  paths:
    - /var/log/*.log
    - /var/log/syslog
    - /var/log/auth.log

processors:
  - add_kubernetes_metadata: ~
  - add_docker_metadata: ~
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: [ "https://es:9200" ]
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl:
    enabled: true
    certificate_authorities: [ "/usr/share/filebeat/certs/ca/ca.crt" ]
