metricbeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.image: "nginx"
          config:
            - module: docker
              metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
              hosts: ["unix:///var/run/docker.sock"]

    - type: kubernetes
      node: ${NODE_NAME}
      templates:
        - condition:
            contains:
              kubernetes.labels.app: "elasticsearch"
          config:
            - module: kubernetes
              metricsets: ["node", "system", "pod", "container", "volume"]
              hosts: ["https://${HOSTNAME}:10250"]
              bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              ssl.certificate_authorities: [ "/usr/share/metricbeat/certs/ca/ca.crt" ]

metricbeat.modules:
- module: system
  metricsets: ["cpu", "memory", "network", "filesystem", "diskio"]
  period: 10s
  enabled: true

- module: docker
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

processors:
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
  - add_host_metadata: ~

output.elasticsearch:
  hosts: [ "https://es:9200" ]
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl:
    enabled: true
    certificate_authorities: [ "/usr/share/metricbeat/certs/ca/ca.crt" ]
