# Followed this to create below ci : https://github.com/maximbetin/maxim-cicd
options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Step 1
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      [
        '-c',
        'docker pull europe-west1-docker.pkg.dev/$PROJECT_ID/movetodata-cr/callisto:$TAG_NAME || exit 0',
      ]
  # Step 2
  - name: gcr.io/cloud-builders/docker
    args:
      [
        'build',
        '-t',
        'europe-west1-docker.pkg.dev/$PROJECT_ID/movetodata-cr/callisto:$TAG_NAME',
        '.',
      ]
  # Step 4
  # - name: 'gcr.io/cloud-builders/kubectl'
  #   args:
  #     [
  #       'set',
  #       'image',
  #       'deployment',
  #       'callisto',
  #       'callisto=europe-west6-docker.pkg.dev/movetodata-211/movetodata-cr/callisto:latest',
  #       '--namespace',
  #       'movetodata',
  #     ]
  #   env:
  #     - 'CLOUDSDK_COMPUTE_ZONE=europe-west6-a'
  #     - 'CLOUDSDK_CONTAINER_CLUSTER=movetodata-211'
  # Push the image to Google Container Registry with the latest tag
images: ['europe-west1-docker.pkg.dev/$PROJECT_ID/movetodata-cr/callisto:$TAG_NAME']
timeout: 7200s
