version: "3.9"

services:
  # Proxies requests to internal services
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy
    depends_on:
      - boson
      - frontend
      # - julia
      # - zoro
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./repos/frontend
    depends_on:
      - boson
    ports:
      - 8081:80
    restart: on-failure

  # all APIs (kitab, passport, fractal)
  boson:
    image: boson
    container_name: boson
    build:
      context: ./repos/boson
    volumes:
      - ./db/bosler:/root/bosler
    depends_on:
      - boson-db
      # - julia
      # - zoro
    ports:
      - 8080:8080
    command: [
        # "./wait-for-it.sh",
        # "boson-db:5432",
        # "--",
        "java",
        "-jar",
        "/app/boson-0.0.1-SNAPSHOT.jar",
      ]
    restart: on-failure
    working_dir: /app

  # database for Boson
  boson-db:
    image: postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/dbscripts/:/docker-entrypoint-initdb.d
    # doesn't work below
    # ports:
    #   - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=solaris

  # # Backend to fractal
  # julia:
  #   image: julia
  #   container_name: julia
  #   build:
  #     context: ./julia
  #   ports:
  #     - 5001:80
  #   restart: on-failure

  # # Backend for Spark
  # zoro:
  #   image: zoro
  #   container_name: zoro
  #   build:
  #     context: ./zoro
  #   ports:
  #     - 5002:5002
  #   restart: on-failure
