
ARG JDK_PACKAGE=openjdk-11.0.2_linux-x64_bin.tar.gz
ARG SPARK_HOME=/opt/spark
ARG JAVA_HOME=/opt/java
ARG SPARK_VERSION=3.4.3
ARG SPARK_PACKAGE=spark-$SPARK_VERSION-bin-hadoop3.tgz

FROM --platform=linux/amd64 gradle:jdk11
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle build --no-daemon -x test

RUN mkdir -p /app/
RUN mv /home/gradle/src/build/libs/*.jar /app/
