name: Build and Deploy to Google Cloud Storage

on:
  push:
    paths:
      - 'Public/**'

env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}

jobs:
  setup-and-deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup - gcloud / gsutil
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        project_id: ${{ secrets.GCS_PROJECT }}
        export_default_credentials: true

    - name: Deploy
      run: |-
        gsutil -m rsync -R Public/ gs://$GCS_BUCKET
