fqdn: dev.orphea.io
containerRegistery: orpheadevacr
namespace: orphea
imagePullPolicy: Always
# repo_path rendered in _helpers.tpl to allow macro:
#   {{ include "orphea-aks.repo_path" . }}

versions:
  platform: 0.1.0
  boson: 0.4.13
  frontend: 0.1.72
  parler: 0.0.13
  julia: 0.0.2
  callisto: 0.0.2
  orpheaDocs: 0.0.3
  sparkHistoryServer: 0.0.2
  connect: 0.0.1

secrets:
  bosonDbUsername: cG9zdGdyZXM=
  bosonDbPassword: c29sYXJpcw==
  minioUsername: bWluaW9taW5pbw==
  minioPassword: bWluaW9taW5pbw==
  fractalTemplatesToken: Z2hwX3hibEphdlNsUkdvMWRKTVB6N0FBT05XYjlVU2lvNzB0N0ozRQ==
  tokenSecret: MDRjYTAyM2IzOTUxMmU0NmQwYzJjZjRiNDhkNWFhYzYxZDM0MzAyOTk0Yzg3Ym9zbGVyZWQ0ZWZmMjI1ZGNmM2IwYTIxODczOWYzODk3MDUxYTA1N2Y5Yjg0NmE2OWVhMjkyN2E1ODcwNDQxNjRiN2JhZTVlMTMwNjIxOWQ1MGI1ODhjYjE=
  googleCloudCredentials: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiZGVjYm9zMjIxLWRldiIsCiAgInByaXZhdGVfa2V5X2lkIjogImFkNmE2YWRkNjcwYTk1NjU0YmNiYzc2OTBhZjdjZTA1YTk0NjlhOWEiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ3hPTzRsdlNXQzlaRC9cblBTN3RpRWxNNC8ydnZPUU5CZE9aT1BrajJpOVI3R2xPeDNVb2Y4am1KZHhCUXVoSStkZHJVeEM0SFQ1RmI5SHpcblowOWcyaG1qQkpnZi83S0YzTUZ1NW5ZbGF3cUxOeWM3d0VmdkYzVUFKOVd3STIxeXJHVlJGb2pRRzFkVFc1L2dcbjRLZ0ZkU2h5Rnc2U1o0Q1J5ZzRLQWJQenN5RWwvc2V3MHRVSDFzTW84bWcwQkJvNmdFTWJUV2t6dllWNHB0WDBcbnRTQU9LbjNJYmhCWmRVYlVpaVA0bmhvdDFydTR6WW8zamNDTUJFQlNoMHhETytXNG1WSmFvY1pSNXRDZEs0RmVcbkE1TjZhMzdvR1Fna0NNRkRxYU5FWXFPdHlaQjArNmZtTWFYaVpma043dW5qOWticGlHWDNhOEM2MWY3dGFBUUxcbkNyMFFQS2FmQWdNQkFBRUNnZ0VBRy82cXUrSm5tUXJTaDBjeWNRbzh6ZjBiMTFWbXp0blRSWnAyM0o5OEp4eEpcbnZFeU1xTU9heUNSRjZUYzQrMElnTWM5eXppcXNhZ3FTWnprMEZGQVBpYTFSbklobk9uY1hSVDM1ZnNxc1pUWm1cbnA2MGxqOUtzUkVTR29HYlFSTE9QNDZIRUpkK1R5VktwYkR3QXZxLzFuaVFmUktnOTZvbTQ4d0syMnZHNmRFWktcbkJrVGVuL3BLVFcya1BzMjd4b1JuSTZFV3pTK2NISFUzcmF0S1NFUTJkSUpiRElOd2hvSGMzaWlmNnlocVRTbytcbkYrNmtiamRkQnUrREs1WnFkdWFGaDNkbDNueVllelVSNGkxRmJZdjZHUHA3VVpQMk1rRmd4T2FzaGJSZUZmL0VcbmNVSmI5SDNieDlVNEFCcEJvUWF0RHRVbVpPbGdkOFVkTDFjUE13TDUzUUtCZ1FEZkk1N1FiTHhIRDkyanhmbWRcblNGc0JxbklIdXMwS0NIUytsdGlPaUE2LzNacFZQSElzdWQ5SEZ4dlFFdWFRSG9ZVE5nNjM5Q0toK1dic1F2QUdcbmlYcFdBZTlvelgyd2l5a09yQ1RqRHVOdGxKYTRrUnVIL0RBMU9GeHBqUUl5cWtpRG1jVmpWb0E3dTlJcGlyWGFcbitBYUxoaXRqY0ZoSjIvMGZKN3VjbE9USUd3S0JnUURMVWoyNStzUmZzU3lRWS9QTVFYdGhhZTFvejFla000US9cbmJlazdCZFNPVDAyTnR5RzI5UTcwTEtpVVVmLzVCTlVhTWpTSHo4am9yN3lJSWZ5UkdMZXZWSlRPZ1BscWRVRmtcblNOSHprd1ptc0lLakozbWpBeHh0RURSdkQrRXpSbFVweVoxdFN3YjY0N21lbjZXWGhTUGlNY3NjQk4vRlBKcUNcbmRUeTlpc0hMelFLQmdRREdjTnd0Q1hhTFQvM1JSeUJORXVyMFdVdWR1aS9jcTFaL3BKRWtlTFY5Uml1WmYrOGRcbi9aTW1tdE4rUVVEUWpJUzZFd29WNkVUZ2ZYZGR4ODNFVW9EOGVpNGFxeDBMWTBiNUtIaUpnVlVhdjlrbWZNM2Fcbktwb0l5bjNNMUwxT3A0ZGptZDRrRU9wcnRRWWJNYU8yLzNwNm5MQjdkNDdjNklwOEtZNjhtdUczWHdLQmdRREFcbkMwZytlSHd2bnB2bkxtSERGajdCdmxuK1c0bitrS0pqZngrREhuaXNpbjlJVWlmSU5pUVB3bmJnMGFzanZNckVcbldaT0FqR1RLVStPUitmZ2ozT0x5K3NNclltc3pnTmxwTGRjUmFGZnRldCtKMStsdWJhdlY0QzZHa01zM3NVRVRcbm5WblROOEM2RFlyd0p2OHo1UkFGd042RjhweWlJaUlYQTBHQ0RxUUtLUUtCZ0FNbHRPRkZQYU1NM01ZdEh6NGhcbjV5NXVDT1NWKzhuSzVwa3BmaERHQStkWEtYR2U0cTdrd1ZqL1JBUThIQmVrQmVnSTJ3YnA3dEJvdU9STDFMZ1ZcbmYrRjNadzliTTIrMzlUb1pITC9CMjh1RzFZOFV2bWRKU3lGZzZGUE1mNzFaRjZwT3BMUGtYQ0IwcWIxMVI5MEJcblAwMXRMMGJrQXFLVTBWTmVJbWRrUUVjcVxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImdvb2dsZS1zdG9yYWdlLXNhQGRlY2JvczIyMS1kZXYuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTAwMzQ0NDE3MjQ3NzA3NjU1NDA3IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9nb29nbGUtc3RvcmFnZS1zYSU0MGRlY2JvczIyMS1kZXYuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iCn0K

backend:
  replicaCount: 1
  swaggerUi: true
  environment: production
  dbHost: "boson-db"
  dbPort: "5432"
  host: "boson"
  generateCertificate: "true"
  backingFs: "hdfs" # possibilites are hdfs | gs | s3 | localfs
  localFsDirectory: "/orphea/demo/localFS"
  hdfsEndpoint: "hdfs://orphea-hdfs-hadoop-hdfs-nn:9000"
  minioEndpoint: "http://minio:9000"
  tokenExpiration: "43200000"
  loadSampleData: "true"
  orpheaMountPath: "/orphea/dev"
  notebookToken: "60c1661cc408f978c309d04157af55c9588ff9557c9380e4fb50785750703da6"
  spark:
    master: "local[*]"
    type:
      dataset: local
      pgSync: local
      columnStats: local
      sql:
        build: kubernetes
        preview: local
      python:
        build: kubernetes
        preview: kubernetes

frontend:
  replicaCount: 1

julia:
  replicaCount: 1
  host: "julia"
  apiPort: "58080"
  gitPort: "58542"
