# NOTE : logDirectory is coming from kubernetes yaml. not used from here

# S3
spark.hadoop.fs.s3a.path.style.access  true
spark.hadoop.fs.s3a.impl         org.apache.hadoop.fs.s3a.S3AFileSystem
# spark.history.fs.logDirectory s3a://spark-streaming/checkpoint/

# GCS
google.cloud.auth.service.account.enable true
google.cloud.auth.service.account.json.keyfile /opt/spark/conf/google_creds.json
# spark.history.fs.logDirectory gs://datasets_collections/spark-streaming/checkpoint/

#  .config("google.cloud.auth.service.account.enable", "true")
#  .config("google.cloud.auth.service.account.json.keyfile", "/opt/spark/conf/google_creds.json")
#             - -Dspark.history.fs.logDirectory=s3a://spark-streaming/checkpoint/
# spark.ui.proxyBase: /bosler-shs
