spring:
  main:
    allow-circular-references: true # This needs removing it is a temporary fix
  banner:
    location: classpath:/banner/movetodata.txt

  datasource:
    initialization-mode: always
    platform: postgres
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/fractal
    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: none
      #      ddl-auto: update
      show-sql: false
    #  main:
    #    allow-bean-definition-overriding: true
    flyway:
      enabled: true
      validate-on-migrate: true
      baselineOnMigrate: true
      location: classpath:db/migration

logging:
  level:
    org:
      springframework:
        security: INFO
#          web:
#            FilterChainProxy: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    supportedSubmitMethods: [ "get", "put", "post", "delete", "options", "head", "patch", "trace" ]
    doc-expansion: none
    persistAuthorization: true
    tryItOutEnabled: true
    syntaxHighlight:
      theme: arta
