services:
  ingress:
    image: nginx:1.17.10
    container_name: ingress
    depends_on:
      - boson
      - frontend
      - orphea-docs
    volumes:
      - ./ingress/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/demo.orphea.io:/etc/nginx/ssl/demo.orphea.io:rw
    ports:
      - "${REVERSE_PROXY_PORT}:${REVERSE_PROXY_PORT}"

  boson:
    privileged: true
    security_opt:
      - label:disable
      - seccomp:unconfined
    image: boson
    container_name: boson
    build:
      context: ./repos/boson
    environment:
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - BASE_URL=${BASE_URL}
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - SWAGGER_UI=${SWAGGER_UI}
      - TOKEN_EXPIRATION=${TOKEN_EXPIRATION}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - LAST_UPDATED_ON=${LAST_UPDATED_ON}
      - VERSION_PLATFORM=${VERSION_PLATFORM}
      - VERSION_ORPHEADOCS=${VERSION_ORPHEADOCS}
      - VERSION_BOSON=${VERSION_BOSON}
      - VERSION_FRONTEND=${VERSION_FRONTEND}
      - VERSION_PARLER=${VERSION_PARLER}
      - NAMESPACE=${NAMESPACE}
      - HOST=${HOST}
      - GENERATE_CERTIFICATE=${GENERATE_CERTIFICATE}
      - ORPHEA_MOUNT_PATH=${ORPHEA_MOUNT_PATH}
      - BACKING_FS=${BACKING_FS}
      - LOCAL_FS_DIRECTORY=${LOCAL_FS_DIRECTORY}
      - SPARK_MASTER=${SPARK_MASTER}
      - FRACTAL_TEMPLATES_PATH=${FRACTAL_TEMPLATES_PATH}
    devices:
      - /dev/fuse:/dev/fuse:rw
    volumes:
      - "${ORPHEA_MOUNT_PATH}:${ORPHEA_MOUNT_PATH}"
      - /var/lib/mycontainer:/var/lib/containers:Z
    depends_on:
      - boson-db
      - boson-redis
    command: ["java", "-jar", "/app/boson-0.0.1-SNAPSHOT.jar"]
    restart: on-failure
    working_dir: /app

  boson-db:
    image: postgres
    container_name: boson-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - "${ORPHEA_MOUNT_PATH}/softwares/postgres/db/data:/var/lib/postgresql/data"
      - "${ORPHEA_MOUNT_PATH}/softwares/postgres/db/dbscripts:/docker-entrypoint-initdb.d"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    image: frontend:latest
    container_name: frontend
    build:
      context: ./repos/frontend
    depends_on:
      - boson
    restart: on-failure

  orphea-docs:
    image: orphea-docs:latest
    container_name: orphea-docs
    build:
      context: ./repos/orphea-docs
    depends_on:
      - boson
    restart: on-failure

  boson-redis:
    image: redis:latest
    container_name: boson-redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server"]
    volumes:
      - ${ORPHEA_MOUNT_PATH}/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
