# Followed this to create below ci : https://github.com/maximbetin/maxim-cicd
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_32'
steps:
  # Step 1
  # - name: "gcr.io/cloud-builders/docker"
  #   entrypoint: "bash"
  #   args:
  #     [
  #       "-c",
  #       "docker pull europe-west1-docker.pkg.dev/$PROJECT_ID/orphea-cr/orphea-docs:latest || exit 0",
  #     ]
  # Step 2
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/orphea-cr/orphea-docs:latest",
        ".",
      ]
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/orphea-cr/orphea-docs:latest"
      ]
  #    dir: 'orphea-docs'
  # Step 3
  #  - name: 'gcr.io/cloud-builders/kubectl'
  #    args: ['apply', '-f', 'k8s/']
  #    env:
  #      - 'CLOUDSDK_COMPUTE_ZONE=europe-west6-a'
  #      - 'CLOUDSDK_CONTAINER_CLUSTER=orphea-dev-1'
  # Step 4
  # - name: "gcr.io/cloud-builders/kubectl"
  #   args:
  #     [
  #       "set",
  #       "image",
  #       "deployment",
  #       "orphea-docs",
  #       "orphea-docs=europe-west1-docker.pkg.dev/$PROJECT_ID/orphea-cr/orphea-docs:latest",
  #       "--namespace",
  #       "orphea",
  #     ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=europe-west1-b"
      - "CLOUDSDK_CONTAINER_CLUSTER=orphea"
    # Push the image to Google Container Registry with the latest tag
images: ["europe-west1-docker.pkg.dev/$PROJECT_ID/orphea-cr/orphea-docs:latest"]
timeout: 7200s