// CREATE GROUP CONSTANTS

export const GROUP_CREATE_REQUEST = "GROUP_CREATE_REQUEST";
export const GROUP_CREATE_SUCCESS = "GROUP_CREATE_SUCCESS";
export const GROUP_CREATE_FAIL = "GROUP_CREATE_FAIL";

// GET ALL GROUPS DATA CONSTANTS

export const GROUP_ALL_REQUEST = "GROUP_ALL_REQUEST";
export const GROUP_ALL_SUCCESS = "GROUP_ALL_SUCCESS";
export const GROUP_ALL_FAIL = "GROUP_ALL_FAIL";

// GET GROUP BY ID CONSTANTS

export const GROUP_DATA_REQUEST = "GROUP_DATA_REQUEST";
export const GROUP_DATA_SUCCESS = "GROUP_DATA_SUCCESS";
export const GROUP_DATA_FAIL = "GROUP_DATA_FAIL";

//  DELETE USER CONSTANTS

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

// MANAGE GROUP CONSTANTS
export const MANAGE_GROUP_REQUEST = "MANAGE_GROUP_REQUEST";
export const MANAGE_GROUP_SUCCESS = "MANAGE_GROUP_SUCCESS";
export const MANAGE_GROUP_FAIL = "MANAGE_GROUP_FAIL";

// GET ALL PERMISSION MAPPINGS
export const PERMISSION_MAPPING_ALL_REQUEST = "PERMISSION_MAPPING_ALL_REQUEST";
export const PERMISSION_MAPPING_ALL_SUCCESS = "PERMISSION_MAPPING_ALL_SUCCESS";
export const PERMISSION_MAPPING_ALL_FAIL = "PERMISSION_MAPPING_ALL_FAIL";

// GET ALL PERMISSION MAPPINGS BY RESOURCE ID
export const PERMISSION_MAPPING_BY_RESOURCEID_REQUEST =
  "PERMISSION_MAPPING_BY_RESOURCEID_REQUEST";
export const PERMISSION_MAPPING_BY_RESOURCEID_SUCCESS =
  "PERMISSION_MAPPING_BY_RESOURCEID_SUCCESS";
export const PERMISSION_MAPPING_BY_RESOURCEID_FAIL =
  "PERMISSION_MAPPING_BY_RESOURCEID_FAIL";

// TO CHECK OWNER OF PROKECT CONSTANTS

export const USER_ROLES_OF_PROJECT_REQUEST = "USER_ROLES_OF_PROJECT_REQUEST";
export const USER_ROLES_OF_PROJECT_SUCCESS = "USER_ROLES_OF_PROJECT_SUCCESS";
export const USER_ROLES_OF_PROJECT_FAIL = "USER_ROLES_OF_PROJECT_FAIL";

// TO DELETE PERMISSION MAPPING

export const DELETE_PERMISSIONS_MAPPING_REQUEST =
  "DELETE_PERMISSIONS_MAPPING_REQUEST";
export const DELETE_PERMISSIONS_MAPPING_SUCCESS =
  "DELETE_PERMISSIONS_MAPPING_FAIL";
export const DELETE_PERMISSIONS_MAPPING_FAIL =
  "DELETE_PERMISSIONS_MAPPING_FAIL";

// NETWORK ERROR ACTIONS
export const SET_NETWORK_ERROR_TRUE = "SET_NETWORK_ERROR_TRUE";
export const SET_NETWORK_ERROR_FALSE = "SET_NETWORK_ERROR_FALSE";

// SSO DETAILS
export const SSO_DETAILS_REQUEST = "SSO_DETAILS_REQUEST";
export const SSO_DETAILS_SUCCESS = "SSO_DETAILS_SUCCESS";
export const SSO_DETAILS_FAIL = "SSO_DETAILS_FAIL";
