export const DASHBOARD_FETCH_REQUEST = "DASHBOARD_FETCH_REQUEST";
export const DASHBOARD_FETCH_SUCCESS = "DASHBOARD_FETCH_SUCCESS";
export const DASHBOARD_FETCH_FAIL = "DASHBOARD_FETCH_FAIL";

export const DASHBOARD_UPDATE_REQUEST = "DASHBOARD_UPDATE_REQUEST";
export const DASHBOARD_UPDATE_SUCCESS = "DASHBOARD_UPDATE_SUCCESS";
export const DASHBOARD_UPDATE_FAIL = "DASHBOARD_UPDATE_FAIL";

export const DASHBOARD_EDIT_REQUEST = "DASHBOARD_EDIT_REQUEST";
export const DASHBOARD_EDIT_SUCCESS = "DASHBOARD_EDIT_SUCCESS";
export const DASHBOARD_EDIT_FAIL = "DASHBOARD_EDIT_FAIL";

export const DASHBOARD_KEY_UPDATE_REQUEST = "DASHBOARD_KEY_UPDATE_REQUEST";
export const DASHBOARD_KEY_UPDATE_SUCCESS = "DASHBOARD_KEY_UPDATE_SUCCESS";
export const DASHBOARD_KEY_UPDATE_FAIL = "DASHBOARD_KEY_UPDATE_FAIL";

export const DASHBOARD_FILTER_REQUEST = "DASHBOARD_FILTER_REQUEST";
export const DASHBOARD_FILTER_SUCCESS = "DASHBOARD_FILTER_SUCCESS";
export const DASHBOARD_FILTER_FAIL = "DASHBOARD_FILTER_FAIL";

export const DASHBOARD_CHART_ACTION_REQUEST = "DASHBOARD_CHART_ACTION_REQUEST";
export const DASHBOARD_CHART_ACTION_SUCCESS = "DASHBOARD_CHART_ACTION_SUCCESS";
export const DASHBOARD_CHART_ACTION_FAIL = "DASHBOARD_CHART_ACTION_FAIL";

export const DASHBOARD_APPLIED_FILTER_REQUEST =
  "DASHBOARD_APPLIED_FILTER_REQUEST";
export const DASHBOARD_APPLIED_FILTER_SUCCESS =
  "DASHBOARD_APPLIED_FILTER_SUCCESS";
export const DASHBOARD_APPLIED_FILTER_FAIL = "DASHBOARD_APPLIED_FILTER_FAIL";

export const DASHBOARD_SUBSCRIBE_REQUEST = "DASHBOARD_SUBSCRIBE_REQUEST";
export const DASHBOARD_SUBSCRIBE_SUCCESS = "DASHBOARD_SUBSCRIBE_SUCCESS";
export const DASHBOARD_SUBSCRIBE_FAIL = "DASHBOARD_SUBSCRIBE_FAIL";

export const DASHBOARD_SUBSCRIBE_UPDATE_REQUEST =
  "DASHBOARD_SUBSCRIBE_UPDATE_REQUEST";
export const DASHBOARD_SUBSCRIBE_UPDATE_SUCCESS =
  "DASHBOARD_SUBSCRIBE_UPDATE_SUCCESS";
export const DASHBOARD_SUBSCRIBE_UPDATE_FAIL =
  "DASHBOARD_SUBSCRIBE_UPDATE_FAIL";

export const DASHBOARD_GRID_CONFIG_REQUEST = "DASHBOARD_GRID_CONFIG_REQUEST";
export const DASHBOARD_GRID_CONFIG_SUCCESS = "DASHBOARD_GRID_CONFIG_SUCCESS";
export const DASHBOARD_GRID_CONFIG_FAIL = "DASHBOARD_GRID_CONFIG_FAIL";

export const DASHBOARD_TAB_CHANGE_SUCCESS = "DASHBOARD_TAB_CHANGE_SUCCESS";
export const DASHBOARD_REFRESH_CONFIG_UPDATE_SUCCESS =
  "DASHBOARD_REFRESH_CONFIG_UPDATE_SUCCESS";
export const DASHBOARD_TRIGGER_SAVE_SUCCESS = "DASHBOARD_TRIGGER_SAVE_SUCCESS";
export const DASHBOARD_REVERT_SAVE_STATUS = "DASHBOARD_REVERT_SAVE_STATUS";
export const DASHBOARD_CHANGE_STATUS = "DASHBOARD_CHANGE_STATUS";
export const DASHBOARD_CHART_ADDED_SUCCESS = "DASHBOARD_CHART_ADDED_SUCCESS";
export const DASHBOARD_CHART_RELOAD_SUCCESS = "DASHBOARD_CHART_RELOAD_SUCCESS";
