// DATASET CREATE CONSTANTS
export const DATASET_CREATE_REQUEST = "DATASET_CREATE_REQUEST";
export const DATASET_CREATE_SUCCESS = "DATASET_CREATE_SUCCESS";
export const DATASET_CREATE_FAIL = "DATASET_CREATE_FAIL";

// DATASET FOOTER BRANCHES CONSTANTS
export const DATASET_BRANCH_REQUEST = "DATASET_BRANCH_REQUEST";
export const DATASET_BRANCH_SUCCESS = "DATASET_BRANCH_SUCCESS";
export const DATASET_BRANCH_FAIL = "DATASET_BRANCH_FAIL";

// DATASET TABLE DATA CONSTANTS
export const DATASET_TABLE_REQUEST = "DATASET_TABLE_REQUEST";
export const DATASET_TABLE_SUCCESS = "DATASET_TABLE_SUCCESS";
export const DATASET_TABLE_FAIL = "DATASET_TABLE_FAIL";

export const DATASET_TABLE_ROW_REQUEST = "DATASET_TABLE_ROW_REQUEST";
export const DATASET_TABLE_ROW_SUCCESS = "DATASET_TABLE_ROW_SUCCESS";
export const DATASET_TABLE_ROW_FAIL = "DATASET_TABLE_ROW_FAIL";

// DATASET TRANSACTIONS CONSTANTS
export const DATASET_TRANSACTIONS_REQUEST = "DATASET_TRANSACTIONS_REQUEST";
export const DATASET_TRANSACTIONS_SUCCESS = "DATASET_TRANSACTIONS_SUCCESS";
export const DATASET_TRANSACTIONS_FAIL = "DATASET_TRANSACTIONS_FAIL";

// DATASET BUILDHISTORY CONSTANTS
export const DATASET_BUILDHISTORY_REQUEST = "DATASET_BUILDHISTORY_REQUEST";
export const DATASET_BUILDHISTORY_SUCCESS = "DATASET_BUILDHISTORY_SUCCESS";
export const DATASET_BUILDHISTORY_FAIL = "DATASET_BUILDHISTORY_FAIL";

// DATASET BUILD CONSTANTS
export const DATASET_BUILD_REQUEST = "DATASET_BUILD_REQUEST";
export const DATASET_BUILD_SUCCESS = "DATASET_BUILD_SUCCESS";
export const DATASET_BUILD_FAIL = "DATASET_BUILD_FAIL";

// DATASET SYNC CONSTANTS
export const DATASET_SYNC_REQUEST = "DATASET_SYNC_REQUEST";
export const DATASET_SYNC_SUCCESS = "DATASET_SYNC_SUCCESS";
export const DATASET_SYNC_FAIL = "DATASET_SYNC_FAIL";

// DATASET BUILDSPEC CONSTANTS
export const DATASET_BUILDSPEC_REQUEST = "DATASET_BUILDSPEC_REQUEST";
export const DATASET_BUILDSPEC_SUCCESS = "DATASET_BUILDSPEC_SUCCESS";
export const DATASET_BUILDSPEC_FAIL = "DATASET_BUILDSPEC_FAIL";

// DATASET BUILDSLOG CONSTANTS
export const DATASET_BUILDLOG_REQUEST = "DATASET_BUILDLOG_REQUEST";
export const DATASET_BUILDLOG_SUCCESS = "DATASET_BUILDLOG_SUCCESS";
export const DATASET_BUILDLOG_FAIL = "DATASET_BUILDLOG_FAIL";

// DATASET DETAILS CONSTANTS FROM FOLDER
export const DATASET_DETAILS_REQUEST = "DATASET_DETAILS_REQUEST";
export const DATASET_DETAILS_SUCCESS = "DATASET_DETAILS_SUCCESS";
export const DATASET_DETAILS_FAIL = "DATASET_DETAILS_FAIL";

// DATASET CONNECT LINK CONSTANTS
export const DATASET_CONNECTLINK_REQUEST = "DATASET_CONNECTLINK_REQUEST";
export const DATASET_CONNECTLINK_SUCCESS = "DATASET_CONNECTLINK_SUCCESS";
export const DATASET_CONNECTLINK_FAIL = "DATASET_CONNECTLINK_FAIL";

// DATASET KEPLER CHART EXIST CONSTANTS
export const DATASET_CHART_EXIST_REQUEST = "DATASET_KEPLER_EXIST_REQUEST";
export const DATASET_CHART_EXIST_SUCCESS = "DATASET_KEPLER_EXIST_SUCCESS";
export const DATASET_CHART_EXIST_FAIL = "DATASET_KEPLER_EXIST_FAIL";

// DATASET SCHEMA CONSTANTS
export const DATASET_SCHEMA_CHANGE_REQUEST = "DATASET_SCHEMA_CHANGE_REQUEST";
export const DATASET_SCHEMA_CHANGE_SUCCESS = "DATASET_SCHEMA_CHANGE_SUCCESS";
export const DATASET_SCHEMA_CHANGE_FAIL = "DATASET_SCHEMA_CHANGE_FAIL";

// DATASET UPLOAD CONSTANTS
export const DATASET_IMPORT_REQUEST = "DATASET_IMPORT_REQUEST";
export const DATASET_IMPORT_SUCCESS = "DATASET_IMPORT_SUCCESS";
export const DATASET_IMPORT_FAIL = "DATASET_IMPORT_FAIL";

// COL STATS PANE CONSTANTS
export const COLUMN_STATS_PANE_OPEN_REQUEST = "COLUMN_STATS_PANE_OPEN_REQUEST";
export const COLUMN_STATS_PANE_OPEN_SUCCESS = "COLUMN_STATS_PANE_OPEN_SUCCESS";
export const COLUMN_STATS_PANE_OPEN_FAIL = "COLUMN_STATS_PANE_OPEN_FAIL";
export const CLEAR_STATS_PANE_STATE = "CLEAR_STATS_PANE_STATE";
export const COLUMN_STATS_PANE_CLOSE = "COLUMN_STATS_PANE_CLOSE";
export const COLUMN_STATS_PANE_CHANGE = "COLUMN_STATS_PANE_CHANGE";

// DATASET EXIST TRANSACTIONS CONSTANTS
export const EXIST_DATASET_TRANSACTION_REQUEST =
  "EXIST_DATASET_TRANSACTION_REQUEST";
export const EXIST_DATASET_TRANSACTION_SUCCESS =
  "EXIST_DATASET_TRANSACTION_SUCCESS";
export const EXIST_DATASET_TRANSACTION_FAIL = "EXIST_DATASET_TRANSACTION_FAIL";

// DATASET MAPPING CONSTANTS
export const DATASET_MAPPING_REQUEST = "DATASET_MAPPING_REQUEST";
export const DATASET_MAPPING_SUCCESS = "DATASET_MAPPING_SUCCESS";
export const DATASET_MAPPING_UPDATE = "DATASET_MAPPING_UPDATE";
export const DATASET_MAPPING_FAIL = "DATASET_MAPPING_FAIL";

export const DATASET_MAPPING_TRANSACTIONS_UPDATE =
  "DATASET_MAPPING_TRANSACTIONS_UPDATE";
