export const FILTERS_DATASET_REQUEST = "FILTERS_DATASET_REQUEST";
export const FILTERS_DATASET_SUCCESS = "FILTERS_DATASET_SUCCESS";
export const FILTERS_DATASET_FAILURE = "FILTERS_DATASET_FAILURE";

export const ADD_FILTERS_FROM_DATASET_SUCCESS =
  "ADD_FILTERS_FROM_DATASET_SUCCESS";
