export const PIPELINE_DETAILS_REQUEST = "PIPELINE_DETAILS_REQUEST";
export const PIPELINE_DETAILS_SUCCESS = "PIPELINE_DETAILS_SUCCESS";
export const PIPELINE_DETAILS_FAIL = "PIPELINE_DETAILS_FAIL";

export const PIPELINE_UPDATE_REQUEST = "PIPELINE_UPDATE_REQUEST";
export const PIPELINE_UPDATE_SUCCESS = "PIPELINE_UPDATE_SUCCESS";
export const PIPELINE_UPDATE_FAIL = "PIPELINE_UPDATE_FAIL";

export const PIPELINE_NAMES_REQUEST = "PIPELINE_NAMES_REQUEST";
export const PIPELINE_NAMES_SUCCESS = "PIPELINE_NAMES_SUCCESS";
export const PIPELINE_NAMES_FAIL = "PIPELINE_NAMES_FAIL";

export const PIPELINE_CREATE_REQUEST = "PIPELINE_CREATE_REQUEST";
export const PIPELINE_CREATE_SUCCESS = "PIPELINE_CREATE_SUCCESS";
export const PIPELINE_CREATE_FAIL = "PIPELINE_CREATE_FAIL";

export const PIPELINE_TREE_REQUEST = "PIPELINE_TREE_REQUEST";
export const PIPELINE_TREE_SUCCESS = "PIPELINE_TREE_SUCCESS";
export const PIPELINE_TREE_FAIL = "PIPELINE_TREE_FAIL";

export const PIPELINE_NODE_DATA_REQUEST = "PIPELINE_NODE_DATA_REQUEST";
export const PIPELINE_NODE_DATA_SUCCESS = "PIPELINE_NODE_DATA_SUCCESS";
export const PIPELINE_NODE_DATA_FAIL = "PIPELINE_NODE_DATA_FAIL";

export const PIPELINE_SELECTED_NODE = "PIPELINE_SELECTED_NODE";

export const SCHEDULE_DETAILS_REQUEST = "SCHEDULE_DETAILS_REQUEST";
export const SCHEDULE_DETAILS_SUCCESS = "SCHEDULE_DETAILS_SUCCESS";
export const SCHEDULE_DETAILS_FAIL = "SCHEDULE_DETAILS_FAIL";

export const SCHEDULE_ADD_REQUEST = "SCHEDULE_ADD_REQUEST";
export const SCHEDULE_ADD_SUCCESS = "SCHEDULE_ADD_SUCCESS";
export const SCHEDULE_ADD_FAIL = "SCHEDULE_ADD_FAIL";

export const SCHEDULE_UPDATE_REQUEST = "SCHEDULE_UPDATE_REQUEST";
export const SCHEDULE_UPDATE_SUCCESS = "SCHEDULE_UPDATE_SUCCESS";
export const SCHEDULE_UPDATE_FAIL = "SCHEDULE_UPDATE_FAIL";

export const SCHEDULE_DELETE_REQUEST = "SCHEDULE_DELETE_REQUEST";
export const SCHEDULE_DELETE_SUCCESS = "SCHEDULE_DELETE_SUCCESS";
export const SCHEDULE_DELETE_FAIL = "SCHEDULE_DELETE_FAIL";

export const PIPELINE_SOURCE_REQUEST = "PIPELINE_SOURCE_REQUEST";
export const PIPELINE_SOURCE_SUCCESS = "PIPELINE_SOURCE_SUCCESS";
export const PIPELINE_SOURCE_FAIL = "PIPELINE_SOURCE_FAIL";

export const PIPELINE_NAME_REQUEST = "PIPELINE_NAME_REQUEST";
export const PIPELINE_NAME_SUCCESS = "PIPELINE_NAME_SUCCESS";
export const PIPELINE_NAME_FAIL = "PIPELINE_NAME_FAIL";

export const PIPELINE_SCHEMA_REQUEST = "PIPELINE_SCHEMA_REQUEST";
export const PIPELINE_SCHEMA_SUCCESS = "PIPELINE_SCHEMA_SUCCESS";
export const PIPELINE_SCHEMA_FAIL = "PIPELINE_SCHEMA_FAIL";
