export const PLATFORM_CONFIG_REQUEST = "PLATFORM_CONFIG_REQUEST";
export const PLATFORM_CONFIG_SUCCESS = "PLATFORM_CONFIG_SUCCESS";
export const PLATFORM_CONFIG_UPDATE = "PLATFORM_CONFIG_UPDATE";
export const PLATFORM_CONFIG_FAIL = "PLATFORM_CONFIG_FAIL";
