export const PROJECT_LIST_REQUEST = "PROJECT_LIST_REQUEST";
export const PROJECT_LIST_SUCCESS = "PROJECT_LIST_SUCCESS";
export const PROJECT_LIST_FAIL = "PROJECT_LIST_FAIL";

export const PROJECT_CREATE_REQUEST = "PROJECT_CREATE_REQUEST";
export const PROJECT_CREATE_SUCCESS = "PROJECT_CREATE_SUCCESS";
export const PROJECT_CREATE_FAIL = "PROJECT_CREATE_FAIL";

export const PROJECT_DETAILS_REQUEST = "PROJECT_DETAILS_REQUEST";
export const PROJECT_DETAILS_SUCCESS = "PROJECT_DETAILS_SUCCESS";
export const PROJECT_DETAILS_FAIL = "PROJECT_DETAILS_FAIL";

export const FOLDER_DETAILS_REQUEST = "FOLDER_DETAILS_REQUEST";
export const FOLDER_DETAILS_SUCCESS = "FOLDER_DETAILS_SUCCESS";
export const FOLDER_DETAILS_FAIL = "FOLDER_DETAILS_FAIL";

export const FOLDER_CREATE_REQUEST = "FOLDER_CREATE_REQUEST";
export const FOLDER_CREATE_SUCCESS = "FOLDER_CREATE_SUCCESS";
export const FOLDER_CREATE_FAIL = "FOLDER_CREATE_FAIL";

export const HEADER_DATA_REQUEST = "HEADER_DATA_REQUEST";
export const HEADER_DATA_SUCCESS = "HEADER_DATA_SUCCESS";
export const HEADER_DATA_FAIL = "HEADER_DATA_FAIL";
