export const QUERY_FETCH_REQUEST = "QUERY_FETCH_REQUEST";
export const QUERY_FETCH_SUCCESS = "QUERY_FETCH_SUCCESS";
export const QUERY_FETCH_FAIL = "QUERY_FETCH_FAIL";

export const QUERY_UPDATE_REQUEST = "QUERY_UPDATE_REQUEST";
export const QUERY_UPDATE_SUCCESS = "QUERY_UPDATE_SUCCESS";
export const QUERY_UPDATE_FAIL = "QUERY_UPDATE_FAIL";

export const QUERY_SLIDER_UPDATE_REQUEST = "QUERY_SLIDER_UPDATE_REQUEST";
export const QUERY_SLIDER_UPDATE_SUCCESS = "QUERY_SLIDER_UPDATE_SUCCESS";
export const QUERY_SLIDER_UPDATE_FAIL = "QUERY_SLIDER_UPDATE_FAIL";
