export const REPO_DETAILS_REQUEST = "REPO_DETAILS_REQUEST";
export const REPO_DETAILS_SUCCESS = "REPO_DETAILS_SUCCESS";
export const REPO_DETAILS_FAIL = "REPO_DETAILS_FAIL";

export const REPO_NODE_DATA_REQUEST = "REPO_NODE_DATA_REQUEST";
export const REPO_NODE_DATA_SUCCESS = "REPO_NODE_DATA_SUCCESS";
export const REPO_NODE_DATA_FAIL = "REPO_NODE_DATA_FAIL";

export const TOGGLE_PREVIEW_PANEL = "TOGGLE_PREVIEW_PANEL";

export const PREVIEW_DATA_REQUEST = "PREVIEW_DATA_REQUEST";
export const PREVIEW_DATA_SUCCESS = "PREVIEW_DATA_SUCCESS";
export const PREVIEW_DATA_FAIL = "PREVIEW_DATA_FAIL";

export const PREVIEW_ID_UPDATE = "PREVIEW_ID_UPDATE";
