export const SOURCE_LIST_REQUEST = "SOURCE_LIST_REQUEST";
export const SOURCE_LIST_SUCCESS = "SOURCE_LIST_SUCCESS";
export const SOURCE_LIST_FAIL = "SOURCE_LIST_FAIL";

export const SOURCE_DELETE_REQUEST = "SOURCE_DELETE_REQUEST";
export const SOURCE_DELETE_SUCCESS = "SOURCE_DELETE_SUCCESS";
export const SOURCE_DELETE_FAIL = "SOURCE_DELETE_FAIL";

export const SOURCE_CREATE_REQUEST = "SOURCE_CREATE_REQUEST";
export const SOURCE_CREATE_SUCCESS = "SOURCE_CREATE_SUCCESS";
export const SOURCE_CREATE_FAIL = "SOURCE_CREATE_FAIL";

export const SOURCE_LINKS_LIST_REQUEST = "SOURCE_LINKS_LIST_REQUEST";
export const SOURCE_LINKS_LIST_SUCCESS = "SOURCE_LINKS_LIST_SUCCESS";
export const SOURCE_LINKS_LIST_FAIL = "SOURCE_LINKS_LIST_FAIL";

export const INITIATE_SOURCE_PREVIEW = "INITIATE_SOURCE_PREVIEW";
export const QUERY_SOURCE = "QUERY_SOURCE";
