export const TOKEN_CREATE_REQUEST = "TOKEN_CREATE_REQUEST";
export const TOKEN_CREATE_SUCCESS = "TOKEN_CREATE_SUCCESS";
export const TOKEN_CREATE_FAIL = "TOKEN_CREATE_FAIL";
export const TOKEN_LIST_REQUEST = "TOKEN_LIST_REQUEST";
export const TOKEN_LIST_SUCCESS = "TOKEN_LIST_SUCCESS";
export const TOKEN_LIST_FAIL = "TOKEN_LIST_FAIL";

export const SET_INVALID_TOKEN = "INVALID_TOKEN";
export const SET_VALID_TOKEN = "VALID_TOKEN";
export const REFRESH_TOKEN_STATUS = "REFRESH_TOKEN_STATUS";
