export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_UPDATE = "USER_DETAILS_UPDATE";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const ALL_USER_DETAILS_REQUEST = "ALL_USER_DETAILS_REQUEST";
export const ALL_USER_DETAILS_SUCCESS = " ALL_USER_DETAILS_SUCCESS ";
export const ALL_USER_DETAILS_FAIL = "ALL_USER_DETAILS_FAIL ";
export const ALL_USER_DETAILS_RESET = "ALL_USER_DETAILS_RESET";

export const USER_BY_ID_REQUEST = "USER_BY_ID_REQUEST";
export const USER_BY_ID_SUCCESS = "USER_BY_ID_SUCCESS";
export const USER_BY_ID_FAIL = "USER_BY_ID_FAIL";

// AUTHORISATION CONSTANTS
export const IS_USER_ADMIN_REQUEST = "IS_USER_ADMIN_REQUEST";
export const IS_USER_ADMIN_SUCCESS = "IS_USER_ADMIN_SUCCESS";
export const IS_USER_ADMIN_FAIL = "IS_USER_ADMIN_FAIL";

export const IS_PROJECT_ADMIN_REQUEST = "IS_PROJECT_ADMIN_REQUEST";
export const IS_PROJECT_ADMIN_SUCCESS = "IS_PROJECT_ADMIN_SUCCESS";
export const IS_PROJECT_ADMIN_FAIL = "IS_PROJECT_ADMIN_FAIL";

export const IS_GROUP_ADMIN_REQUEST = "IS_GROUP_ADMIN_REQUEST";
export const IS_GROUP_ADMIN_SUCCESS = "IS_GROUP_ADMIN_SUCCESS";
export const IS_GROUP_ADMIN_FAIL = "IS_GROUP_ADMIN_FAIL";

export const IS_PLATFORM_ADMIN_REQUEST = "IS_PLATFORM_ADMIN_REQUEST";
export const IS_PLATFORM_ADMIN_SUCCESS = "IS_PLATFORM_ADMIN_SUCCESS";
export const IS_PLATFORM_ADMIN_FAIL = "IS_PLATFORM_ADMIN_FAIL";

export const IS_CONNECT_ADMIN_REQUEST = "IS_CONNECT_ADMIN_REQUEST";
export const IS_CONNECT_ADMIN_SUCCESS = "IS_CONNECT_ADMIN_SUCCESS";
export const IS_CONNECT_ADMIN_FAIL = "IS_CONNECT_ADMIN_FAIL";
export const IS_LOGEDIN_WITH_OTP = "IS_LOGEDIN_WITH_OTP";
export const IS_LOGEDIN_WITH_RECOVERYCODE = "IS_LOGEDIN_WITH_RECOVERYCODE";
export const IS_LOGEDIN_WITH_CREDENTIALS = "IS_LOGEDIN_WITH_OTP_CREDENTIALS";
