export const VERSION_UPDATE_SUCCESS = "VERSION_UPDATE_SUCCESS";
export const VERSION_DASH_CHANGE = "VERSION_DASH_CHANGE";
export const VERSION_CHART_CHANGE = "VERSION_CHART_CHANGE";
export const VERSION_AUTOSAVE_CHECK = "VERSION_AUTOSAVE_CHECK";
export const LATEST_VERSION = "0";
