server:
  port: 7376
  max-http-header-size: 32000
  tomcat:
    max-swallow-size: 20GB
    accesslog:
      enabled: true
      directory: "/movetodata/snap/logs/accessLogs"
      prefix: "${spring.application.name}"
      pattern: '%{dd/MMM/yyyy}t %{begin:HH:mm:ss.SSS}t %{end:HH:mm:ss.SSS}t %{RequestId}i %r %s %h %b %T %{Referer}i "%{User-agent}i"'
    basedir: ${log.path:./}
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
    include-stacktrace: never
  #  ssl:
  #    key-store: classpath:springboot.p12
  #    key-store-password: shalimar
  #    key-store-type: pkcs12
  #    key-alias: springboot
  #    key-password: shalimar
#  port: 7845
spring:
  banner:
    location: classpath:/banner/movetodata.txt
  sql:
    init:
      schema-locations: classpath:db/quartz_tables_h2.sql
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:capture
    password: ''

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    #      ddl-auto: update
    show-sql: false
  #  main:
  #    allow-bean-definition-overriding: true

#  quartz:
#    properties:
#      org:
#        quartz:
#          jobStore:
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate

file:
  upload-dir=/Users/rakeshmalik/movetodata/uploads

logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        security: DEBUG
#          web:
#            FilterChainProxy: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    supportedSubmitMethods: ["get", "put", "post", "delete", "options", "head", "patch", "trace"]
    doc-expansion: none
    persistAuthorization: true
    tryItOutEnabled: true
    syntaxHighlight:
      theme: arta
    disable-swagger-default-url: false
log:
  api:
    lastLogTimestampEndpoint: ${UPDATE_HOST}/api/logging/getLastLogTimeStamp/{deploymentId}/{metricType}
    metric:
      diskMetricsEndpoint: ${UPDATE_HOST}/api/logging/diskMetricLogs/{deploymentId}/{metricType}
      memoryMetricsEndpoint: ${UPDATE_HOST}/api/logging/memoryMetricLogs/{deploymentId}/{metricType}
      swapMetricsEndpoint: ${UPDATE_HOST}/api/logging/swapMetricLogs/{deploymentId}/{metricType}
      cpuMetricsEndpoint: ${UPDATE_HOST}/api/logging/cpuMetricLogs/{deploymentId}/{metricType}
    boson:
  #    endpoint: http://localhost:8080/api/logging/applicationLogs/{deploymentId}
      appLogEndpoint: ${UPDATE_HOST}/api/logging/applicationLogs/{deploymentId}/{metricType}
      accessLogEndpoint: ${UPDATE_HOST}/api/logging/accessLogs/{deploymentId}/{metricType}
    capture:
      appLogEndpoint: ${UPDATE_HOST}/api/logging/captureApplicationLogs/{deploymentId}/{metricType}

