alter table if exists kepler_chart_config_filter add constraint UK_98pgmk5wahcge569a7yx2yu7 unique (filter_id);
alter table if exists kepler_chart_config_series add constraint UK_r12ca4xxgcl0t6l1ogfskq9ss unique (series_id);
alter table if exists kepler_chart_filter_filters add constraint UK_qfmd1igonrtwpnxjdi2qdps9u unique (filters_id);
alter table if exists kitab_branches add constraint UKnbhedef4sd6a8c0quqnd448um unique (dataset_id, branch, repository_id);
alter table if exists kitab_comments_replies add constraint UK_5ob87dbbp0co2btuo0vv64yos unique (replies_id);
alter table if exists kitab_dataset_branches add constraint UK_4xvf25stsspxj98qhxxrg89ib unique (branches_id);
alter table if exists kitab_dataset_schema add constraint UKtqndbixfekxklspblxmopxuwc unique (dataset_id, branch, transaction_id);
alter table if exists kitab_dataset_stats add constraint UKbhp2pi84nc7uo5918bju7ltaj unique (dataset_id, branch);
alter table if exists bob_build_log_messages add constraint FKkolm633yftp6i420865ds0iwk foreign key (build_id_finished) references bob_build_log;
alter table if exists bob_build_log_messages add constraint FKh1x9pi8x5psmjg5ddnhhha3r8 foreign key (build_id_preparing) references bob_build_log;
alter table if exists bob_build_log_messages add constraint FKiefn9n28587pyl9y7lisjkkr9 foreign key (build_id_running) references bob_build_log;
alter table if exists bob_build_log_messages add constraint FKgio3d1h5mqmh3v16sdfjfabq9 foreign key (build_id_starting) references bob_build_log;
alter table if exists docket_tags add constraint FKb0w8kfktct3st3kxlu1jb45js foreign key (tags_category_id) references docket_tag_category;
alter table if exists kepler_chart_config_filter add constraint FKo08d6fr09h88d0dwatxk15i5w foreign key (filter_id) references kepler_chart_filter;
alter table if exists kepler_chart_config_filter add constraint FKsip4o0p4y8cpiph83e8mlcr5c foreign key (chart_config_model_id) references kepler_chart_config;
alter table if exists kepler_chart_config_series add constraint FKq1o6g5p4u1asi00tf686ubf4l foreign key (series_id) references kepler_chart_series;
alter table if exists kepler_chart_config_series add constraint FKbmv28damip954ovwyyy0giipg foreign key (chart_config_model_id) references kepler_chart_config;
alter table if exists kepler_chart_filter_filters add constraint FKpf6aig22g21ppirtcq4msxgsu foreign key (filters_id) references kepler_dataset_filter;
alter table if exists kepler_chart_filter_filters add constraint FKdwkdqxnsp5xygd7ccgjr6wjgi foreign key (dataset_filter_model_id) references kepler_chart_filter;
alter table if exists kepler_charts add constraint FK9px4ska3mnhxg1dhd7mnmro8x foreign key (chart_config_id) references kepler_chart_config;
alter table if exists kepler_charts add constraint FKeipxerqarqq95e5meywby0cyx foreign key (chart_customize_id) references kepler_chart_customize;
alter table if exists kepler_charts_dashboard add constraint FK4axt19d6pk3mldbbxlvr1qlhw foreign key (dashboard_id, dashboard_version_id) references kepler_dashboards;
alter table if exists kepler_charts_dashboard add constraint FKelsbmlp2b8tyqg367abext19i foreign key (charts_id, charts_version_id) references kepler_charts;
alter table if exists kepler_tab_elements add constraint FKel73pa36ggfcycvold53ull7j foreign key (tabs_id) references kepler_tabs;
alter table if exists kepler_tabs add constraint FKq27rtotyq4a9u4ufs0s5yd7e7 foreign key (dashboard_id_fk, version_id_fk) references kepler_dashboards;
alter table if exists kepler_tabs_charts_for_tabs add constraint FKhvidulesalcj4q6qfqfyg7fqe foreign key (charts_for_tabs_id, charts_for_tabs_version_id) references kepler_charts;
alter table if exists kepler_tabs_charts_for_tabs add constraint FKfd4p6wvrix9fn3lhufdpgrt29 foreign key (tabs_for_charts_id) references kepler_tabs;
alter table if exists kitab_comments_replies add constraint FKcttmjjpk6w83xqw06m7b7cm24 foreign key (replies_id) references kitab_comments;
alter table if exists kitab_comments_replies add constraint FK48vy64h3x42y0ly2t33d5lylh foreign key (comment_model_id) references kitab_comments;
alter table if exists kitab_dataset_branches add constraint FK2u79lfhuc2u7yomx5r6f7dfd4 foreign key (branches_id) references kitab_branches;
alter table if exists kitab_dataset_branches add constraint FKe8c7i4k202yciwpcndnvgalej foreign key (dataset_model_id) references kitab_dataset;
alter table if exists kitab_dataset_schema add constraint FKbogmacw7wpp3kx0yxdt3ijvk3 foreign key (rg_fk) references kitab_dataset_custom_schema;
alter table if exists kitab_dataset_tags add constraint FKsag5ekb7xb0sd45rjq93ur22e foreign key (tag_id) references docket_tags;
alter table if exists kitab_dataset_tags add constraint FKbhjl4hc722v9cvwp8okc94bji foreign key (dataset_id) references kitab_dataset;
alter table if exists kitab_folder add constraint FKbewi3hkg7l6db972534nj48gd foreign key (parent_id) references kitab_folder;
alter table if exists kitab_folder add constraint FKlqub6ybebo8k1agxxx5v8ousm foreign key (created_by_id) references passport_users;
alter table if exists kitab_folder add constraint FK1xfy3oep9d4ooaqpwtg1m5wiv foreign key (updated_by_id) references passport_users;
alter table if exists kitab_resource_version_details add constraint FKtpk316hkvsiev3hv2samb23qt foreign key (resource_id) references kitab_resource_versions;
alter table if exists kitab_resource_version_details_changes_wrapper add constraint FK6rb1qoo9uoxd9ap9i26ig5ekt foreign key (resource_version_details_id_fk) references kitab_resource_version_details;
alter table if exists kitab_resource_version_details_changes_wrapper add constraint FKrgorkilhmodei5282gj2d5ucm foreign key (resource_version_details) references kitab_resource_version_details;
alter table if exists kitab_resource_version_details_changes_wrapper_changes add constraint FKqq4ck7nh5m9vthgpsdmk59rf9 foreign key (changes_wrapper_id_fk) references kitab_resource_version_details_changes_wrapper;
alter table if exists kitab_resource_version_details_changes_wrapper_changes add constraint FK5ausinkcuhu4b9ibgmhynv15u foreign key (changes_wrapper) references kitab_resource_version_details_changes_wrapper;
alter table if exists passport_groups_managers add constraint FKmqgn46sy7lnxbab7pg6ol6cup foreign key (managers_id) references passport_users;
alter table if exists passport_groups_managers add constraint FK7vm05h6vn5uyfan7l3e1pxnyv foreign key (groups_id) references passport_groups;
alter table if exists passport_groups_members add constraint FKr4byrfhghap8q048w8j91h7yo foreign key (members_id) references passport_users;
alter table if exists passport_groups_members add constraint FKiawu6w0jhtaft1wneq45cekp0 foreign key (groups_id) references passport_groups;
alter table if exists passport_groups_owners add constraint FKddmwvbjlumtafaafha38s5did foreign key (owners_id) references passport_users;
alter table if exists passport_groups_owners add constraint FKfc6ete5ptlxyjjhx1jnit9147 foreign key (groups_id) references passport_groups;
alter table if exists passport_permissions_mapping add constraint FKc2lvfpf0t3dy3ogqu3tn494t2 foreign key (rg_fk) references passport_role;
alter table if exists passport_users add constraint FKertnf3v8xmi5rls5dokx12qgx foreign key (preferences_id) references passport_users_preferences;
alter table if exists postgres_sync_specification_index_names add constraint FKqpd6hc4mlvigf7gb6gcaepo76 foreign key (postgres_sync_specification_id) references synchro_postgres_sync_specifications;
ALTER TABLE if exists scheduler_job_info_triggers ADD CONSTRAINT uc_scheduler_job_info_triggers_triggers_triggerid UNIQUE (triggers_trigger_id);
ALTER TABLE if exists scheduler_job_info_triggers ADD CONSTRAINT fk_schjobinftri_on_scheduler_job_info FOREIGN KEY (scheduler_job_info_job_id) REFERENCES scheduler_job_info (job_id);
ALTER TABLE if exists scheduler_job_info_triggers ADD CONSTRAINT fk_schjobinftri_on_trigger_model FOREIGN KEY (triggers_trigger_id) REFERENCES schedule_trigger (trigger_id);
alter table if exists sources_agent_id add constraint FK5i3vrfcxgp367jxg3fqnrmcn2 foreign key (sources_id) references connect_sources;
ALTER TABLE if exists dataset_mapping_transaction ADD CONSTRAINT FK_ZORODATASETMAPPINGTRANSACTIO_ON_DATASETMAPPINGMODELDATASETID FOREIGN KEY (dataset_mapping_model_dataset_id) REFERENCES dataset_mapping (dataset_id);