apiVersion: v1
kind: PersistentVolume
metadata:
  name: boson-pv
  namespace: bosler
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/bosler" # this is for bosler storage which should ideally be in S3

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boson-pvc
  namespace: bosler
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: boson-pv
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: boson
  name: boson
  namespace: bosler
spec:
  replicas: 1
  selector:
    matchLabels:
      name: boson
  template:
    metadata:
      labels:
        name: boson
    spec:
      containers:
        - args:
            - java
            - -jar
            - -Dspring.profiles.active=kubernetes
            - /app/boson-0.0.1-SNAPSHOT.jar
          image: europe-west1-docker.pkg.dev/bosler-bnp/bosler-cr/boson:latest
          imagePullPolicy: IfNotPresent
          name: boson
          ports:
            - containerPort: 8080
          resources: {}
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bosler-secret
                  key: boson-db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bosler-secret
                  key: boson-db-password
            - name: DB_HOST
              value: boson-db
            - name: DB_PORT
              value: "5432"
            - name: JULIA_BASE_PATH
              value: "/root/bosler/git/remote"
            - name: HOST
              value: "boson"
            - name: GENERATE_CERTIFICATE
              value: "false"
            - name: JULIA_HOST
              value: "julia"              
            - name: JULIA_API_PORT
              value: "58080"
            - name: JULIA_PORT
              value: "58542"
            - name: MINIO_ENDPOINT
              value: "http://minio:9000"
            - name: SPARK_PYSPARK_IMAGE
              value: "europe-west1-docker.pkg.dev/bosler-bnp/bosler-cr/funnel:latest"
            - name: LOAD_SAMPLE_DATA
              value: "true"  
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bosler-secret
                  key: jwt-secret
            - name: FRACTAL_TEMPLATES_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bosler-secret
                  key: fractal-templates-token
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: bosler-secret
                  key: minio-username
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: bosler-secret
                  key: minio-password
          volumeMounts:
            - mountPath: /root/bosler
              name: boson-app-pv
          workingDir: /app
      restartPolicy: Always
      volumes:
        - name: boson-app-pv
          persistentVolumeClaim:
            claimName: boson-pvc

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: boson
  name: boson
  namespace: bosler
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "bosler-backend-config"}'
spec:
  type: NodePort
  ports:
    - name: boson
      port: 8080
      targetPort: 8080
  selector:
    name: boson
status:
  loadBalancer: {}
