apiVersion: v1
kind: PersistentVolume
metadata:
  name: boson-db-pv
  namespace: bosler
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/bosler" # this is for bosler db storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boson-db-pvc
  namespace: bosler
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: boson-db-pv
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: database
  name: boson-db
  namespace: bosler
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  selector:
    matchLabels:
      service: boson-db
  template:
    metadata:
      labels:
        service: boson-db
    spec:
      containers:
        - name: boson-db
          image: postgres:11-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: bosler-secret
                  key: boson-db-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bosler-secret
                  key: boson-db-password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-volume-mount
              subPath: postgres
          # command: ["/bin/sh"]
          # args:
          #   - -c
          #   - >-
          #     su - postgres -c "psql -c 'CREATE DATABASE boson;'"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: boson-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: boson-db
  namespace: bosler
  labels:
    service: boson-db
spec:
  selector:
    service: boson-db
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
