apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: movetodata
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/movetodata" # this is for movetodata storage which should ideally be in S3

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: movetodata
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: minio-pv
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: minio
  name: minio
  namespace: movetodata
spec:
  replicas: 1
  selector:
    matchLabels:
      name: minio
  template:
    metadata:
      labels:
        name: minio
    spec:
      containers:
        - args:
            - server
            - /storage
          image: minio/minio:latest
          imagePullPolicy: IfNotPresent
          name: minio
          ports:
            - containerPort: 9000
              hostPort: 9000
          resources: {}
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: minio-username
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: minio-password
          volumeMounts:
            - mountPath: /storage
              name: minio-pv
          workingDir: /app
      restartPolicy: Always
      volumes:
        - name: minio-pv
          persistentVolumeClaim:
            claimName: minio-pvc

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: minio
  name: minio
  namespace: movetodata
spec:
  type: NodePort
  ports:
    - name: minio
      port: 9000
      targetPort: 9000
  selector:
    name: minio
status:
  loadBalancer: {}
