apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movetodata-ingress
  namespace: movetodata
  annotations:
    kubernetes.io/ingress.global-static-ip-name: movetodata
    ingress.gcp.kubernetes.io/pre-shared-cert: movetodata-preshared-cert
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: bnp.movetodata.io
    - http:
        paths:
          - path: /api/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: boson
                port:
                  number: 8080
          - path: /movetodata-shs/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: movetodata-spark-history-server
                port:
                  number: 18080
          - path: /lsp/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: parler
                port:
                  number: 8999
          # - path: /julia/*
          #   pathType: ImplementationSpecific
          #   backend:
          #     service:
          #       name: boson
          #       port:
          #         number: 58542
          - path: /swagger-ui/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: boson
                port:
                  number: 8080
          - path: /swagger-ui.html
            pathType: ImplementationSpecific
            backend:
              service:
                name: boson
                port:
                  number: 8080
          - path: /v3/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: boson
                port:
                  number: 8080
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80
