apiVersion: v1
description: HDFS backing filesystem for MoveToData
name: hadoop
version: 1.1.4
appVersion: 2.9.0
home: https://hadoop.apache.org/
sources:
- https://github.com/apache/hadoop
icon: http://hadoop.apache.org/images/hadoop-logo.jpg
deprecated: false
