apiVersion: v1
kind: Secret
metadata:
  name: bosler-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  boson-db-username: {{ .Values.secrets.bosonDbUsername }}
  boson-db-password: {{ .Values.secrets.bosonDbPassword }}
  minio-username: {{ .Values.secrets.minioUsername }}
  minio-password: {{ .Values.secrets.minioPassword }}
  fractal-templates-token: {{ .Values.secrets.fractalTemplatesToken }}
  token-secret: {{ .Values.secrets.tokenSecret }}
  google-cloud-credentials: {{ .Values.secrets.googleCloudCredentials }}
