apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: capture
  name: capture
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      name: capture
  template:
    metadata:
      labels:
        name: capture
    spec:
      containers:
        - args:
            - java
            - -jar
            - -Dspring.profiles.active=kubernetes
            - /app/capture-0.0.1-SNAPSHOT.jar
          image: "{{ include "bosler-gke.repo_path" . }}capture:{{ .Values.versions.capture }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          name: capture
          ports:
            - containerPort: 8080
          resources: {}
          env:
            - name: BUNDLE_DIR
              value: "/bosler/dev"
            - name: DEPLOYMENT_ID
              value: "be0dc428-7431-4dea-bf1b-4afdf2890b20"
            - name: HELM_CHART
              value: "bosler-gke"
            - name: HELM_VALUES
              value: "devCluster.yaml"
            - name: TOKEN
              value: "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1MjVmNzg1NS1jNGViLTQxMTctOTY2Ni1kZjNhN2Y0NDcyN2UiLCJpYXQiOjE3MTY1NjQ4NDgsImV4cCI6MTc3ODcwOTYwMH0.1LieP0fJSUXKaU1EZvLRVcApKNhYa4cyLzzI4x7mD4Wvd7fzIF-_Gd31QlW3EWuQzMoZBjRW2vHb3U8Kap3Ilw"
            - name: UPDATE_HOST
              value: "https://snap.bosler.io:8082"
            - name: SWAGGER_UI
              value: "{{ .Values.backend.swaggerUi }}"
            - name : ALLOWED_ORIGINS
              value: "{{ include "bosler-gke.allowedOrigins" . }}"
            - name: TOKEN_EXPIRATION
              value: "{{ .Values.backend.tokenExpiration }}"
          volumeMounts:
            - mountPath: "{{ .Values.backend.boslerMountPath }}"
              name: bosler-local-fs
          workingDir: "{{ .Values.backend.boslerMountPath }}"
      restartPolicy: Always
      volumes:
        - name: bosler-local-fs
          hostPath:
            path: "{{ .Values.backend.boslerMountPath }}"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: capture
  name: capture
  namespace: {{ .Values.namespace }}
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "bosler-backend-config"}'
spec:
  type: NodePort
  ports:
    - name: capture
      port: 8080
      targetPort: 8080
  selector:
    name: capture
status:
  loadBalancer: {}
