apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bosler-ingress
  namespace: bosler
  annotations:
    kubernetes.io/ingress.global-static-ip-name: bosler
    ingress.gcp.kubernetes.io/pre-shared-cert: bosler-preshared-cert
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
    - host: dev.bosler.io
    - http:
        paths:
          - path: /api/jupyter/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: callisto
                port:
                  number: 8686
          - path: /api/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: boson
                port:
                  number: 8080
          #- path: /bosler-shs/*
          #  pathType: ImplementationSpecific
          #  backend:
          #    service:
          #      name: bosler-spark-history-server
          #      port:
          #        number: 18080
          - path: /lsp/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: parler
                port:
                  number: 8999
          # - path: /julia/*
          #   pathType: ImplementationSpecific
          #   backend:
          #     service:
          #       name: boson
          #       port:
          #         number: 58542
          - path: /swagger-ui/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: boson
                port:
                  number: 8080
          - path: /swagger-ui.html
            pathType: ImplementationSpecific
            backend:
              service:
                name: boson
                port:
                  number: 8080
          - path: /v3/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: boson
                port:
                  number: 8080
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80
