apiVersion: v1
kind: Secret
metadata:
  name: bosler-secret
  namespace: bosler
type: Opaque
data:
  boson-db-username: cG9zdGdyZXM=
  boson-db-password: c29sYXJpcw==
  # dockerhub token 6bff1c32-b338-461c-a8d9-2c1f125edd5b
  minio-username: bWluaW9taW5pbw==
  minio-password: bWluaW9taW5pbw==
  fractal-templates-token: Z2hwXzB1VlNhNGwyNkE0ZGQyNzFkeXFqSnprZzMydzY1YTFzUXRkZg==
  token-secret: MDRjYTAyM2IzOTUxMmU0NmQwYzJjZjRiNDhkNWFhYzYxZDM0MzAyOTk0Yzg3Ym9zbGVyZWQ0ZWZmMjI1ZGNmM2IwYTIxODczOWYzODk3MDUxYTA1N2Y5Yjg0NmE2OWVhMjkyN2E1ODcwNDQxNjRiN2JhZTVlMTMwNjIxOWQ1MGI1ODhjYjE=
  google-cloud-credentials: google-storage-sa
