apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: frontend
  name: frontend
  namespace: movetodata
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
        - image: europe-west1-docker.pkg.dev/octbos22/movetodata-cr/frontend:latest
          imagePullPolicy: Always
          name: frontend
          ports:
            - containerPort: 80
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: frontend
  name: frontend
  namespace: movetodata
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "movetodata-backend-config"}'
spec:
  type: NodePort
  ports:
    - name: frontend
      port: 80
      targetPort: 80
  selector:
    name: frontend
status:
  loadBalancer: {}
