apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: orphea-backend-config
  namespace: orphea
spec:
  timeoutSec: 1800
  connectionDraining:
    drainingTimeoutSec: 1800
  sessionAffinity:
    affinityType: "CLIENT_IP"
    affinityCookieTtlSec: 1800
  securityPolicy:
    name: orphea
