# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: boson-pvc
#   namespace: orphea
#   labels:
#     type: local
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   volumeName: boson-pv
#   storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: callisto
  name: callisto
  namespace: orphea
spec:
  replicas: 1
  selector:
    matchLabels:
      name: callisto
  template:
    metadata:
      labels:
        name: callisto
    spec:
      containers:
        - image: europe-west1-docker.pkg.dev/orphea-334213/orphea-cr/callisto:latest
          imagePullPolicy: Always
          name: callisto
          ports:
            - containerPort: 8686
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: orphea-secret
                  key: boson-db-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orphea-secret
                  key: boson-db-password
            - name: POSTGRES_DATABASE
              value: boson
            - name: POSTGRES_PORT
              value: "5432"
            - name: JULIA_BASE_PATH
              value: "/root/orphea/git/remote"
            - name: POSTGRES_HOST
              value: "10.90.240.2"
            - name: GENERATE_CERTIFICATE
              value: "true"
            - name: JULIA_HOST
              value: "julia"              
            - name: JULIA_API_PORT
              value: "58080"
            - name: JULIA_PORT
              value: "58542"
            - name: BACKING_FS
              value: "gs"
            - name: GS_BUCKET
              value: "datasets_collections_septbos22"
            - name: MINIO_ENDPOINT
              value: "http://minio:9000"
            - name: ORPHEA_API
              value: "https://dev.orphea.io"              
            - name: NOTEBOOK_DIR
              value: "/root/"              
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: orphea-secret
                  key: token-secret
            - name: FRACTAL_TEMPLATES_TOKEN
              valueFrom:
                secretKeyRef:
                  name: orphea-secret
                  key: fractal-templates-token
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: orphea-secret
                  key: minio-username
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: orphea-secret
                  key: minio-password
            - name: GOOGLE_CLOUD_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: orphea-secret
                  key: google-cloud-credentials
                  
          volumeMounts:
            - mountPath: /root/orphea
              name: boson-app-pv
          workingDir: /app
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: boson-app-pv
          persistentVolumeClaim:
            claimName: boson-pvc

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: callisto
  name: callisto
  namespace: orphea
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "orphea-backend-config"}'
spec:
  type: NodePort
  ports:
    - name: callisto
      port: 8686
      targetPort: 8686
  selector:
    name: callisto
status:
  loadBalancer: {}
