apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: parler
  name: parler
  namespace: bosler
spec:
  replicas: 1
  selector:
    matchLabels:
      name: parler
  template:
    metadata:
      labels:
        name: parler
    spec:
      containers:
        - args:
            - npm
            - run
            - start:main
          image: europe-west1-docker.pkg.dev/bosler-334213/bosler-cr/parler:latest
          imagePullPolicy: Always
          name: parler
          ports:
            - containerPort: 8999
          # ports:
          #   - containerPort: 8998
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: parler
  name: parler
  namespace: bosler
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "bosler-backend-config"}'
spec:
  type: NodePort
  ports:
    - name: parler
      port: 8999
      targetPort: 8999
    # - name: parler-secure
    #   port: 8998
    #   targetPort: 8998
  selector:
    name: parler
status:
  loadBalancer: {}
