apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: redis
  name: boson-redis
  namespace: "{{ .Values.namespace }}"
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  selector:
    matchLabels:
      service: boson-redis
  template:
    metadata:
      labels:
        service: boson-redis
    spec:
      containers:
        - name: boson-redis
          image: redis:latest
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: orphea-volume
              subPath: redis
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: orphea-volume
          persistentVolumeClaim:
            claimName: orphea-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: boson-redis
  namespace: "{{ .Values.namespace }}"
  labels:
    service: boson-redis
spec:
  selector:
    service: boson-redis
  type: NodePort
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
