#server:
#  error:
#    include-message: always
#    include-binding-errors: always
#    include-exception: false
#    include-stacktrace: never

#  ssl:
#    key-store: classpath:springboot.p12
#    key-store-password: shalimar
#    key-store-type: pkcs12
#    key-alias: springboot
#    key-password: shalimar
#  port: 8443

spring:
#  main:
#    allow-circular-references: true # This needs removing it is a temporary fix
  banner:
    location: classpath:/banner/bosler.txt
  datasource:
    initialization-mode: always
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/boson
    driver-class-name: org.postgresql.Driver
#  datasource:
#    initialization-mode: always
#    platform: postgres
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/boson
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  jpa:
#    generate-ddl: true
#    hibernate:
#      ddl-auto: none
#    #      ddl-auto: update
#    show-sql: false
#  #  main:
#  #    allow-bean-definition-overriding: true
  flyway:
    enabled: true
    validate-on-migrate: true
    baselineOnMigrate: true
    location: classpath:db/migration

#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: 3abb0171750efb190893
#            client-secret: 6bf37822a8b404bce995804d536fd19ead2fe1b6
#            redirectUri: ${BASE_URL}/api/oauth2/callback/{registrationId}
#            scope:
#              - email
#              - profile
#          google:
#            client-id: 677716313541-sp7pnv293eige85rd2d5821jfc1n13te.apps.googleusercontent.com
#            client-secret: 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
#            redirectUri: ${BASE_URL}/api/oauth2/callback/{registrationId}
#            scope:
#              - email
#              - profile

#          facebook:
#            clientId: 1317868399042498
#            clientSecret: 1e3d041eafb9c489a2e5b367d01c7525
#            redirectUri: ${BASE_URL}/api/oauth2/callback/{registrationId}
#            scope:
#              - email
#              - public_profile
#
#        provider:
#          facebook:
#            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
#            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
#            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50000MB
      max-request-size: 51555MB

  quartz:
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
#  jackson:
#    serialization:
#      fail-on-empty-beans: false
app:
  auth:
    tokenSecret: ${TOKEN_SECRET}
    tokenExpirationMsec: ${TOKEN_EXPIRATION}            # 12 hours
  cors:
    allowedOrigins: ${ALLOWED_ORIGINS}
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - ${BASE_URL}/oauth2/redirect

application:
  security:
    jwt:
      secret-key: ${TOKEN_SECRET}
      expiration: ${TOKEN_EXPIRATION} # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  cors:
    allowedOrigins: ${ALLOWED_ORIGINS}

  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - ${BASE_URL}/oauth2/redirect
      -
#file:
#  upload-dir=/User/rakeshmalik/bosler/uploads

logging:
  level:
    org:
      springframework:
        security: INFO

springdoc:
  api-docs:
    enabled: ${SWAGGER_UI}
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    supportedSubmitMethods: [ "get", "put", "post", "delete", "options", "head", "patch", "trace" ]
    doc-expansion: none
    persistAuthorization: true
    tryItOutEnabled: true
    syntaxHighlight:
      theme: arta
