apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: boson
  name: boson
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      name: boson
  template:
    metadata:
      labels:
        name: boson
    spec:
      containers:
        - args:
            - java
            - -jar
            - -Dspring.profiles.active=kubernetes
            - /app/boson-0.0.1-SNAPSHOT.jar
          image: "{{ include "movetodata-aks.repo_path" . }}boson:{{ .Values.versions.boson }}"
          imagePullPolicy: Always
          name: boson
          ports:
            - containerPort: 8080
          resources: {}
          env:
            - name: LAST_UPDATED_ON
              value: "{{ now | unixEpoch  }}"
            - name: VERSION-platform
              value: "{{ .Values.versions.platform }}"              
            - name: VERSION-movetodataDocs
              value: "{{ .Values.versions.movetodataDocs }}"
            - name: VERSION-boson
              value: "{{ .Values.versions.boson }}"
            - name: VERSION-callisto
              value: "{{ .Values.versions.callisto }}"
            - name: VERSION-frontend
              value: "{{ .Values.versions.frontend }}"
            - name: VERSION-julia
              value: "{{ .Values.versions.julia }}"
            - name: VERSION-parler
              value: "{{ .Values.versions.parler }}"
            - name: VERSION-sparkHistoryServer
              value: "{{ .Values.versions.sparkHistoryServer }}"
            - name: NAMESPACE
              value: "{{ .Values.namespace }}"
            - name: SWAGGER_UI
              value: "{{ .Values.backend.swaggerUi }}"
            - name: BASE_URL
              value: "{{ include "movetodata-aks.baseUrl" . }}"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: boson-db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: boson-db-password
            - name: DB_HOST
              value: "{{ .Values.backend.dbHost }}"
            - name: DB_PORT
              value: "{{ .Values.backend.dbPort }}"
            - name: HOST
              value: "{{ .Values.backend.host }}"
            - name: GENERATE_CERTIFICATE
              value: "{{ .Values.backend.generateCertificate }}"
            - name: MOVETODATA_MOUNT_PATH
              value: "{{ .Values.backend.movetodataMountPath }}"              
            - name: GIT_CLONED_PATH
              value: "{{ .Values.backend.movetodataMountPath }}/git/cloned"
            - name: BACKING_FS
              value: "{{ .Values.backend.backingFs }}"
            - name: LOCAL_FS_DIRECTORY
              value: "{{ .Values.backend.localFsDirectory }}"
            - name: HDFS_ENDPOINT
              value: "{{ .Values.backend.hdfsEndpoint }}"                       
            - name: MINIO_ENDPOINT
              value: "{{ .Values.backend.minioEndpoint }}"
            - name : ALLOWED_ORIGINS
              value: "{{ include "movetodata-aks.allowedOrigins" . }}"
            - name: TOKEN_EXPIRATION
              value: "{{ .Values.backend.tokenExpiration }}"
            - name: SPARK_MASTER
              value: "{{ .Values.backend.spark.master }}"
            - name: IMAGE_PULL_POLICY
              value: "{{ .Values.imagePullPolicy }}"
            - name: BUILD_IMAGE
              value: "{{ include "movetodata-aks.repo_path" . }}boson:{{ .Values.versions.boson }}"       
            - name: LOAD_SAMPLE_DATA
              value: "{{ .Values.backend.loadSampleData }}"           
            - name: FRACTAL_TEMPLATES_PATH
              value: "/app/FractalTemplates"
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: token-secret
            # - name: FRACTAL_TEMPLATES_TOKEN
            #   valueFrom:
            #     secretKeyRef:
            #       name: movetodata-secret
            #       key: fractal-templates-token                  
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: minio-username
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: minio-password
            - name: GOOGLE_CLOUD_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: google-cloud-credentials
          volumeMounts:
            - mountPath: "{{ .Values.backend.movetodataMountPath }}"
              name: movetodata-volume
          workingDir: "{{ .Values.backend.movetodataMountPath }}"
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      volumes:
        - name: movetodata-volume
          persistentVolumeClaim:
            claimName: movetodata-nfs-pvc

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: boson
  name: boson
  namespace: {{ .Values.namespace }}
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "movetodata-backend-config"}'
spec:
  type: NodePort
  ports:
    - name: boson
      port: 8080
      targetPort: 8080
  selector:
    name: boson
status:
  loadBalancer: {}