apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: movetodata-docs
  name: movetodata-docs
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: movetodata-docs
  template:
    metadata:
      labels:
        name: movetodata-docs
    spec:
      containers:
        - image: "{{ include "movetodata-aks.repo_path" . }}movetodata-docs:{{ .Values.versions.movetodataDocs }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          name: movetodata-docs
          ports:
            - containerPort: 80
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: movetodata-docs
  name: movetodata-docs
  namespace: {{ .Values.namespace }}
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "movetodata-backend-config"}'
spec:
  type: NodePort
  ports:
    - name: movetodata-docs
      port: 80
      targetPort: 80
  selector:
    name: movetodata-docs
status:
  loadBalancer: {}
