apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movetodata-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-alias: "{{ .Values.fqdn }}"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    # - host: "{{ .Values.fqdn }}"  
    - http:
        paths:
          - path: /api/jupyter/
            pathType: Prefix
            backend:
              service:
                name: callisto
                port:
                  number: 8686
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: boson
                port:
                  number: 8080
          # - path: /movetodata-shs/
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: movetodata-spark-history-server
          #       port:
          #         number: 18080
          - path: /lsp/
            pathType: Prefix
            backend:
              service:
                name: parler
                port:
                  number: 8999
          # - path: /docs/
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: movetodata-docs
          #       port:
          #         number: 80
          - path: /learn/
            pathType: Prefix
            backend:
              service:
                name: movetodata-docs
                port:
                  number: 80
          # - path: /julia/
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: boson
          #       port:
          #         number: 58542
          - path: /swagger-ui/
            pathType: Prefix
            backend:
              service:
                name: boson
                port:
                  number: 8080
          - path: /swagger-ui.html
            pathType: Prefix
            backend:
              service:
                name: boson
                port:
                  number: 8080
          - path: /v3/
            pathType: Prefix
            backend:
              service:
                name: boson
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
