apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: parler
  name: parler
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: parler
  template:
    metadata:
      labels:
        name: parler
    spec:
      containers:
        - args:
            - npm
            - run
            - start:main
          image: "{{ include "orphea-gke.repo_path" . }}parler:{{ .Values.versions.parler }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          name: parler
          ports:
            - containerPort: 8999
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: parler
  name: parler
  namespace: {{ .Values.namespace }}
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "orphea-backend-config"}'
spec:
  type: NodePort
  ports:
    - name: parler
      port: 8999
      targetPort: 8999
    # - name: parler-secure
    #   port: 8998
    #   targetPort: 8998
  selector:
    name: parler
status:
  loadBalancer: {}
