# Followed this to create below ci : https://github.com/maximbetin/maxim-cicd
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_32'
steps:
  # Step 1
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker pull europe-west1-docker.pkg.dev/$PROJECT_ID/movetodata-cr/frontend-auth:latest || exit 0",
      ]
  # Step 2
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/movetodata-cr/frontend-auth:latest",
        ".",
      ]
  #    dir: 'frontend'
  # Step 3
  #  - name: 'gcr.io/cloud-builders/kubectl'
  #    args: ['apply', '-f', 'k8s/']
  #    env:
  #      - 'CLOUDSDK_COMPUTE_ZONE=europe-west6-a'
  #      - 'CLOUDSDK_CONTAINER_CLUSTER=movetodata-dev-1'
  # Step 4
  # - name: "gcr.io/cloud-builders/kubectl"
  #   args:
  #     [
  #       "set",
  #       "image",
  #       "deployment",
  #       "frontend",
  #       "frontend=europe-west1-docker.pkg.dev/$PROJECT_ID/movetodata-cr/frontend:latest",
  #       "--namespace",
  #       "movetodata",
  #     ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=europe-west1-b"
      - "CLOUDSDK_CONTAINER_CLUSTER=movetodata"
    # Push the image to Google Container Registry with the latest tag
images: ["europe-west1-docker.pkg.dev/$PROJECT_ID/movetodata-cr/frontend-auth:latest"]
timeout: 7200s
