fqdn: test.bosler.io
computeRegion: europe-west2
computeZone: europe-west2-b
containerRegistery: bosler-cr
projectId: aprbos23
namespace: bosler-test
imagePullPolicy: IfNotPresent
# repo_path rendered in _helpers.tpl to allow macro:
#   {{ include "bosler-gke.repo_path" . }}

secrets:
  bosonDbUsername: cG9zdGdyZXM=
  bosonDbPassword: c29sYXJpcw==
  minioUsername: bWluaW9taW5pbw==
  minioPassword: bWluaW9taW5pbw==
  fractalTemplatesToken: Z2hwXzB1VlNhNGwyNkE0ZGQyNzFkeXFqSnprZzMydzY1YTFzUXRkZg==
  tokenSecret: MDRjYTAyM2IzOTUxMmU0NmQwYzJjZjRiNDhkNWFhYzYxZDM0MzAyOTk0Yzg3Ym9zbGVyZWQ0ZWZmMjI1ZGNmM2IwYTIxODczOWYzODk3MDUxYTA1N2Y5Yjg0NmE2OWVhMjkyN2E1ODcwNDQxNjRiN2JhZTVlMTMwNjIxOWQ1MGI1ODhjYjE=
  googleCloudCredentials: None

backend:
  replicaCount: 1
  swaggerUi: true
  dbHost: "boson-db"
  dbPort: "5432"
  host: "boson"
  generateCertificate: "true"
  backingFs: "localfs" # possibilites are hdfs | gs | s3 | localfs
  localFsDirectory: "/bosler/test/localFS"
  hdfsEndpoint: "hdfs://bosler-hdfs-hadoop-hdfs-nn:9000"
  minioEndpoint: "http://minio:9000"
  tokenExpiration: "43200000"
  loadSampleData: "true"
  boslerMountPath: "/bosler/test"
  notebookToken: "60c1661cc408f978c309d04157af55c9588ff9557c9380e4fb50785750703da6"
  spark:
    master: "local[*]"
    type: kubernetes
    columnStatsType: local
    sqlBuildType: local

frontend:
  replicaCount: 1

julia:
  replicaCount: 0
  host: "julia"
  apiPort: "58080"
  gitPort: "58542"
