---
- name: Install common utilties on All Vm's
  hosts: all_vms
  become: yes
  become_method: sudo
  become_user: root
  vars:
    ansible_become_pass: "bosler2024"
  tasks:
    # - name: Echo the current username
    #   command: whoami
    #   register: username_output  # Register the output of the command

    # - name: Display the username
    #   debug:
    #     msg: "The current user on {{ inventory_hostname }} is {{ username_output.stdout }}"

    - name: Copy visudo script
      copy:
        src: /home/dexter/Work/bosler/unify/ansible/scripts/visudo.sh
        dest: /tmp/visudo.sh
        mode: "0755"
        force: yes

    - name: Copy hosts script
      copy:
        src: /home/dexter/Work/bosler/unify/ansible/scripts/hosts.sh
        dest: /tmp/hosts.sh
        mode: "0755"
        force: yes

    - name: Copy swapoff script
      copy:
        src: /home/dexter/Work/bosler/unify/ansible/scripts/swapoff.sh
        dest: /tmp/swapoff.sh
        mode: "0755"
        force: yes

    - name: Copy hostname script
      copy:
        src: /home/dexter/Work/bosler/unify/ansible/scripts/hostname.sh
        dest: /tmp/hostname.sh
        mode: "0755"
        force: yes

    - name: Copy NFS script
      copy:
        src: /home/dexter/Work/bosler/unify/ansible/scripts/nfs.sh
        dest: /tmp/nfs.sh
        mode: "0755"
        force: yes

    - name: Copy containerd script
      copy:
        src: /home/dexter/Work/bosler/unify/ansible/scripts/containerd.sh
        dest: /tmp/containerd.sh
        mode: "0755"
        force: yes

    - name: Run the visudo script
      shell: "/tmp/visudo.sh"
      register: script_output
      no_log: false

    - name: Run the swapoff script
      shell: "/tmp/swapoff.sh"
      register: script_output
      no_log: false

    - name: Run the hosts script
      shell: "/tmp/hosts.sh"
      register: script_output
      no_log: false

    - name: Run the hostname script
      shell: "/tmp/hostname.sh {{ inventory_hostname }}"
      register: script_output
      no_log: false

    - name: Run the NFS script
      shell: "/tmp/nfs.sh"
      register: script_output
      no_log: false

    - name: Run the containerd script
      shell: "/tmp/containerd.sh"
      register: script_output
      no_log: false

    - name: Display script output
      debug:
        msg: "Script output: {{ script_output.stdout }}"
