---
- name: Install Helm, Containerd, Postgres, Redis on bosler-db
  hosts: db
  become: yes
  become_method: sudo
  become_user: root
  vars:
    ansible_become_pass: "bosler2024"
  tasks:
    # - name: Echo the current username
    #   command: whoami
    #   register: username_output  # Register the output of the command

    # - name: Display the username
    #   debug:
    #     msg: "The current user on {{ inventory_hostname }} is {{ username_output.stdout }}"

    - name: Copy postgres script
      copy:
        src: /home/dexter/Work/bosler/unify/ansible/scripts/postgres.sh
        dest: /tmp/postgres.sh
        mode: "0755"
        force: yes

    - name: Copy redis script
      copy:
        src: /home/dexter/Work/bosler/unify/ansible/scripts/redis.sh
        dest: /tmp/redis.sh
        mode: "0755"
        force: yes

    - name: Copy helm script
      copy:
        src: /home/dexter/Work/bosler/unify/ansible/scripts/helm.sh
        dest: /tmp/helm.sh
        mode: "0755"
        force: yes

    - name: Run the postgres script
      shell: "/tmp/postgres.sh"
      register: script_output
      no_log: false

    - name: Run the redis script
      shell: "/tmp/redis.sh"
      register: script_output
      no_log: false

    - name: Run the helm script
      shell: "/tmp/helm.sh"
      register: script_output
      no_log: false

    - name: Display script output
      debug:
        msg: "Script output: {{ script_output.stdout }}"
