options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Step 1
#  - name: 'gcr.io/cloud-builders/docker'
#    entrypoint: 'bash'
#    args: [
#        '-c',
#        'docker pull europe-west2-docker.pkg.dev/$PROJECT_ID/orphea-cr/boson:latest || exit 0'
#    ]
  # Step 2
  - name: gcr.io/cloud-builders/docker
    args: [
        'build',
        '-t',
        'europe-west2-docker.pkg.dev/$PROJECT_ID/orphea-cr/boson:latest',
        '.'
    ]

  - name: gcr.io/cloud-builders/docker
    args: [
        'push',
        'europe-west2-docker.pkg.dev/$PROJECT_ID/orphea-cr/boson:latest'
    ]
  # Step 4
#  - name: 'gcr.io/cloud-builders/kubectl'
#    args: [
#        'set',
#        'image',
#        'deployment',
#        'boson',
#        'boson=europe-west2-docker.pkg.dev/$PROJECT_ID/orphea-cr/boson:latest',
#        '--namespace',
#        'orphea'
#    ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west2-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=orphea'
images: [
    'europe-west2-docker.pkg.dev/$PROJECT_ID/orphea-cr/boson:latest'
]
timeout: 2400s

