name: Automated Run Trigger

on:
  push:
    branches:
      - main
      - feature

jobs:
  handle_push:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Action
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            ID="${{ secrets.MAIN_TRIGGER_ID }}"
          elif [ "${{ github.ref_name }}" == "feature" ]; then
            ID="${{ secrets.FEATURE_TRIGGER_ID }}"
          fi
          curl -X GET "https://snap.orphea.io:8082/api/build/trigger/run/${ID}" \
          -H "Authorization: Bearer ${{ secrets.SNAP_TOKEN }}" \
          -H "Content-Type: application/json"
