apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: movetodata-spark-history-server
  name: movetodata-spark-history-server
  namespace: movetodata
spec:
  replicas: 1
  selector:
    matchLabels:
      name: movetodata-spark-history-server
  template:
    metadata:
      labels:
        name: movetodata-spark-history-server
    spec:
      containers:
        - name: movetodata-spark-history-server
          image: europe-west6-docker.pkg.dev/movetodata-dev2/movetodata-cr/spark-history-server:latest

          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"

          command:
            - /usr/bin/tini
            - -s
            - --
            - /opt/spark/bin/spark-class
            - -Dspark.history.fs.logDirectory=s3a://spark-streaming/checkpoint/
            - org.apache.spark.deploy.history.HistoryServer

          ports:
            - name: http
              protocol: TCP
              containerPort: 18080

          readinessProbe:
            timeoutSeconds: 4
            httpGet:
              path: /
              port: http

          livenessProbe:
            timeoutSeconds: 4
            httpGet:
              path: /
              port: http

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: movetodata-spark-history-server
  name: movetodata-spark-history-server
  namespace: movetodata
spec:
  type: LoadBalancer
  ports:
    - name: movetodata-spark-history-server
      port: 18080
      targetPort: 18080
  selector:
    name: movetodata-spark-history-server
status:
  loadBalancer: {}
