export const ALL_ARTIFACT_DETAILS_REQUEST = "ALL_ARTIFACT_DETAILS_REQUEST";
export const ALL_ARTIFACT_DETAILS_SUCCESS = " ALL_ARTIFACT_DETAILS_SUCCESS ";
export const ALL_ARTIFACT_DETAILS_FAIL = "ALL_ARTIFACT_DETAILS_FAIL ";
export const ALL_ARTIFACT_DETAILS_RESET = "ALL_ARTIFACT_DETAILS_RESET";
