export const ALL_CONFIGURATION_DETAILS_REQUEST = "ALL_CONFIGURATION_DETAILS_REQUEST";
export const ALL_CONFIGURATION_DETAILS_SUCCESS = " ALL_CONFIGURATION_DETAILS_SUCCESS ";
export const ALL_CONFIGURATION_DETAILS_FAIL = "ALL_CONFIGURATION_DETAILS_FAIL ";
export const ALL_CONFIGURATION_DETAILS_RESET = "ALL_CONFIGURATION_DETAILS_RESET";
