export const ALL_DEPLOYMENT_DETAILS_REQUEST = "ALL_DEPLOYMENT_DETAILS_REQUEST";
export const ALL_DEPLOYMENT_DETAILS_SUCCESS = " ALL_DEPLOYMENT_DETAILS_SUCCESS ";
export const ALL_DEPLOYMENT_DETAILS_FAIL = "ALL_DEPLOYMENT_DETAILS_FAIL ";
export const ALL_DEPLOYMENT_DETAILS_RESET = "ALL_DEPLOYMENT1_DETAILS_RESET";
