export const LANGUAGE_FETCH_REQUEST = "LANGUAGE_FETCH_REQUEST";
export const LANGUAGE_FETCH_SUCCESS = "LANGUAGE_FETCH_SUCCESS";
export const LANGUAGE_FETCH_FAIL = "LANGUAGE_FETCH_FAIL";

export const LANGUAGE_UPDATE_REQUEST = "LANGUAGE_UPDATE_REQUEST";
export const LANGUAGE_UPDATE_SUCCESS = "LANGUAGE_UPDATE_SUCCESS";
export const LANGUAGE_UPDATE_FAIL = "LANGUAGE_UPDATE_FAIL";
