export const ALL_TRIGGER_DETAILS_REQUEST = "ALL_TRIGGER_DETAILS_REQUEST";
export const ALL_TRIGGER_DETAILS_SUCCESS = " ALL_TRIGGER_DETAILS_SUCCESS ";
export const ALL_TRIGGER_DETAILS_FAIL = "ALL_TRIGGER_DETAILS_FAIL ";
export const ALL_TRIGGER_DETAILS_RESET = "ALL_TRIGGER_DETAILS_RESET";
