options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Step 1 Get the latest docker image from google artifact repository
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker pull europe-west1-docker.pkg.dev/decbos221-dev/orphea-cr/orpheaio-wordpress-$BRANCH_NAME:latest || exit 0",
      ]
    id: DockerPull

  # Step 2 Build Docker image for latest code pushh
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '--network=cloudbuild'
      - '-t'
      - 'europe-west1-docker.pkg.dev/decbos221-dev/orphea-cr/orpheaio-wordpress-$BRANCH_NAME:latest'
      - .
      - '-f'
      - Dockerfile
    id: Build

  # Step 3 Push Docker image to artifact repository
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "europe-west1-docker.pkg.dev/decbos221-dev/orphea-cr/orpheaio-wordpress-$BRANCH_NAME:latest"
      ]
    id: DockerPush

    # Step 4 gcloud run service
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: [ 'run', 'deploy', 'orpheaio-wordpress-$BRANCH_NAME', '--project', 'decbos221-dev', '--image', 'europe-west1-docker.pkg.dev/decbos221-dev/orphea-cr/orpheaio-wordpress-$BRANCH_NAME:latest', '--region', 'europe-west1', '--platform', 'managed',
            '--set-env-vars', 'ORPHEA_PROJECT_ID=decbos221-dev,ORPHEA_SERVICE_NAME=orpheaio-wordpress']
    id: Cloud Deploy
    # Push the image to Google Container Registry with the latest tag
images: [ "europe-west1-docker.pkg.dev/decbos221-dev/orphea-cr/orpheaio-wordpress-$BRANCH_NAME:latest" ]
timeout: 2400s