apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      #- 10.132.0.240-10.132.0.250
      # change above to ip you want to expose before kubectl apply -f apply metallb-configmap.yaml

