spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

server.error.include-message=always

spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/Template
spring.datasource.username=postgres
spring.datasource.password=solaris

spring.datasource.initialization-mode=always

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=create-drop

#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

springdoc.api-docs.path=/api-docs
# swagger-ui custom path
springdoc.swagger-ui.path=/movetodata-api.html
#springdoc.swagger-ui.disable-swagger-default-url=true
#springdoc.swagger-ui.enabled=false
#springdoc.api-docs.enabled=false