apiVersion: v1
kind: PersistentVolume
metadata:
  name: boson-pv
  namespace: movetodata
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp" # this is for movetodata storage which should ideally be in S3

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boson-pvc
  namespace: movetodata
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: boson
  name: boson
  namespace: movetodata
spec:
  replicas: 1
  selector:
    matchLabels:
      name: boson
  template:
    metadata:
      labels:
        name: boson
    spec:
      containers:
        - args:
            - java
            - -jar
            - -Dspring.profiles.active=kubernetes
            - /app/boson-0.0.1-SNAPSHOT.jar
          image: rmalik/movetodata:boson
          imagePullPolicy: Always
          name: boson
          ports:
            - containerPort: 8080
          resources: {}
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: boson-db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: boson-db-password
            - name: DB_HOST
              value: boson-db
            - name: DB_PORT
              value: "5432"
            - name: JULIA_URL
              value: "http://julia:58542/"
            - name: MINIO_ENDPOINT
              value: "http://minio:9000"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: minio-username
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: minio-password
          volumeMounts:
            - mountPath: /root/movetodata
              name: boson-pv
          workingDir: /app
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      volumes:
        - name: boson-pv
          persistentVolumeClaim:
            claimName: boson-pvc

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: boson
  name: boson
  namespace: movetodata
spec:
  ports:
    - name: boson
      port: 8080
      targetPort: 8080
  selector:
    name: boson
status:
  loadBalancer: {}
