apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: orphea
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp" # works differently on GKE
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: orphea
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: minio
  name: minio
  namespace: orphea
spec:
  replicas: 1
  selector:
    matchLabels:
      name: minio
  template:
    metadata:
      labels:
        name: minio
    spec:
      containers:
        - args:
            - server
            - /storage
          image: minio/minio:latest
          imagePullPolicy: Always
          name: minio
          ports:
            - containerPort: 9000
              hostPort: 9000
          resources: {}
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: orphea-secret
                  key: minio-username
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: orphea-secret
                  key: minio-password
          volumeMounts:
            - mountPath: /root/orphea
              name: minio-pv
          workingDir: /app
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      volumes:
        - name: minio-pv
          persistentVolumeClaim:
            claimName: minio-pvc

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: minio
  name: minio
  namespace: orphea
spec:
  ports:
    - name: minio
      port: 9000
      targetPort: 9000
  selector:
    name: minio
status:
  loadBalancer: {}
