apiVersion: v1
kind: PersistentVolume
metadata:
  name: julia-pv
  namespace: movetodata
spec:
  storageClassName: "standard"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: julia-pvc
  gcePersistentDisk:
    pdName: movetodata-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: julia-pvc
  namespace: movetodata
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: julia
  name: julia
  namespace: movetodata
spec:
  replicas: 1
  selector:
    matchLabels:
      name: julia
  template:
    metadata:
      labels:
        name: julia
    spec:
      containers:
        - args:
            - java
            - -jar
            - -Dspring.profiles.active=kubernetes
            - /app/julia-0.0.1-SNAPSHOT-all.jar
          image: rmalik/movetodata:julia
          imagePullPolicy: Always
          name: julia
          ports:
            - containerPort: 58542
          resources: {}
          env:
            - name: HOST
              value: "julia"
            - name: JULIA_PORT
              value: "58542"
            - name: JULIA_BASE_PATH
              value: "/root/movetodata"
          volumeMounts:
            - mountPath: /root/movetodata
              name: julia-pv
          workingDir: /app
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      volumes:
        - name: julia-pv
          persistentVolumeClaim:
            claimName: julia-pvc

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: julia
  name: julia
  namespace: movetodata
spec:
  ports:
    - name: julia
      port: 58542
      targetPort: 58542
  selector:
    name: julia
status:
  loadBalancer: {}
