/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.bosler.sparkoperator.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1beta2SparkApplicationSpecDriverValueFromConfigMapKeyRef
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-07T11:53:46.903Z[Etc/UTC]")
public class V1beta2SparkApplicationSpecDriverValueFromConfigMapKeyRef {
    public static final String SERIALIZED_NAME_KEY = "key";
    public static final String SERIALIZED_NAME_NAME = "name";
    public static final String SERIALIZED_NAME_OPTIONAL = "optional";
    @SerializedName(SERIALIZED_NAME_KEY)
    private String key;
    @SerializedName(SERIALIZED_NAME_NAME)
    private String name;
    @SerializedName(SERIALIZED_NAME_OPTIONAL)
    private Boolean optional;


    public V1beta2SparkApplicationSpecDriverValueFromConfigMapKeyRef key(String key) {

        this.key = key;
        return this;
    }

    /**
     * Get key
     *
     * @return key
     **/
    @ApiModelProperty(required = true, value = "")

    public String getKey() {
        return key;
    }


    public void setKey(String key) {
        this.key = key;
    }


    public V1beta2SparkApplicationSpecDriverValueFromConfigMapKeyRef name(String name) {

        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getName() {
        return name;
    }


    public void setName(String name) {
        this.name = name;
    }


    public V1beta2SparkApplicationSpecDriverValueFromConfigMapKeyRef optional(Boolean optional) {

        this.optional = optional;
        return this;
    }

    /**
     * Get optional
     *
     * @return optional
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getOptional() {
        return optional;
    }


    public void setOptional(Boolean optional) {
        this.optional = optional;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationSpecDriverValueFromConfigMapKeyRef v1beta2SparkApplicationSpecDriverValueFromConfigMapKeyRef = (V1beta2SparkApplicationSpecDriverValueFromConfigMapKeyRef) o;
        return Objects.equals(this.key, v1beta2SparkApplicationSpecDriverValueFromConfigMapKeyRef.key) &&
                Objects.equals(this.name, v1beta2SparkApplicationSpecDriverValueFromConfigMapKeyRef.name) &&
                Objects.equals(this.optional, v1beta2SparkApplicationSpecDriverValueFromConfigMapKeyRef.optional);
    }

    @Override
    public int hashCode() {
        return Objects.hash(key, name, optional);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta2SparkApplicationSpecDriverValueFromConfigMapKeyRef {\n");
        sb.append("    key: ").append(toIndentedString(key)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    optional: ").append(toIndentedString(optional)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

