export const enum SourceTypeEnum {
  JDBC = "JDBC",
  POSTGRES = "POSTGRES",
  MYSQL = "MYSQL",
  ORACLE21 = "ORACLE21",
  MSSQLSERVER = "MSSQLSERVER",
  MARIADB = "MARIADB",
  SNOWFLAKE = "SNOWFLAKE",
  ODBC = "ODBC",
  CLICKHOUSE = "CLICKHOUSE",
  DATABRICKS = "DATABRICKS",
  MONGODB = "MONGODB",
}
