name: Build and Deploy to Google Cloud Storage

on:
  push:
    paths:
    - 'GKE_sandpit/hello-world-basic-gce/whitelist.txt'

jobs:
  setup-and-deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup - gcloud / gsutil
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
        export_default_credentials: true

    - name: Deploy
      run: |-
        WHITELIST=$(paste -s -d, GKE_sandpit/hello-world-basic-gce/whitelist.txt)
        SECPOLICY="hello-world"
        gcloud compute security-policies rules update 1000 \
          --security-policy "${SECPOLICY}" \
          --description "allow traffic from whitelist.txt" \
          --src-ip-ranges "${WHITELIST}" \
          --action "allow"
