# renew_before_expiry = 30 days
version = 0.31.0
archive_dir = /etc/letsencrypt/archive/berto.bosler.io
cert = /etc/letsencrypt/live/berto.bosler.io/cert.pem
privkey = /etc/letsencrypt/live/berto.bosler.io/privkey.pem
chain = /etc/letsencrypt/live/berto.bosler.io/chain.pem
fullchain = /etc/letsencrypt/live/berto.bosler.io/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = d6a3d5016705f6f46f47fccdf5f4ecd5
authenticator = webroot
server = https://acme-v02.api.letsencrypt.org/directory
[[webroot_map]]
berto.bosler.io = /letsencrypt
