# renew_before_expiry = 30 days
version = 0.31.0
archive_dir = /etc/letsencrypt/archive/berto.movetodata.fr
cert = /etc/letsencrypt/live/berto.movetodata.fr/cert.pem
privkey = /etc/letsencrypt/live/berto.movetodata.fr/privkey.pem
chain = /etc/letsencrypt/live/berto.movetodata.fr/chain.pem
fullchain = /etc/letsencrypt/live/berto.movetodata.fr/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = d6a3d5016705f6f46f47fccdf5f4ecd5
authenticator = webroot
server = https://acme-v02.api.letsencrypt.org/directory
[[webroot_map]]
berto.movetodata.fr = /letsencrypt
