# renew_before_expiry = 30 days
version = 0.31.0
archive_dir = /etc/letsencrypt/archive/demo.orphea.fr
cert = /etc/letsencrypt/live/demo.orphea.fr/cert.pem
privkey = /etc/letsencrypt/live/demo.orphea.fr/privkey.pem
chain = /etc/letsencrypt/live/demo.orphea.fr/chain.pem
fullchain = /etc/letsencrypt/live/demo.orphea.fr/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = d6a3d5016705f6f46f47fccdf5f4ecd5
authenticator = webroot
server = https://acme-v02.api.letsencrypt.org/directory
[[webroot_map]]
demo.orphea.fr = /letsencrypt
