# renew_before_expiry = 30 days
version = 0.31.0
archive_dir = /etc/letsencrypt/archive/demo.bosler.io
cert = /etc/letsencrypt/live/demo.bosler.io/cert.pem
privkey = /etc/letsencrypt/live/demo.bosler.io/privkey.pem
chain = /etc/letsencrypt/live/demo.bosler.io/chain.pem
fullchain = /etc/letsencrypt/live/demo.bosler.io/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = d6a3d5016705f6f46f47fccdf5f4ecd5
authenticator = webroot
server = https://acme-v02.api.letsencrypt.org/directory
webroot_path = /letsencrypt,
[[webroot_map]]
aurora.bosler.io = /letsencrypt
bora.bosler.io = /letsencrypt
buran.bosler.io = /letsencrypt
nexus.bosler.io = /letsencrypt
