apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: julia
  name: julia
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.julia.replicaCount }}
  selector:
    matchLabels:
      name: julia
  template:
    metadata:
      labels:
        name: julia
    spec:
      containers:
        - args:
            - java
            - -jar
            - -Dspring.profiles.active=kubernetes
            - /app/julia-0.0.1-SNAPSHOT.jar
          image: "{{ include "movetodata-gke.repo_path" . }}julia:{{ .Values.versions.julia }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          name: julia
          ports:
            - containerPort: {{ .Values.julia.gitPort }}
          resources: {}
          env:
            - name: JULIA_HOST
              value: "{{ .Values.julia.host }}"
            - name: JULIA_API_PORT
              value: "{{ .Values.julia.apiPort }}"
            - name: JULIA_PORT
              value: "{{ .Values.julia.gitPort }}"
            - name: JULIA_BASE_PATH
              value: "{{ .Values.backend.movetodataMountPath }}/git/remote"
            - name: BACKING_FS
              value: "{{ .Values.backend.backingFs }}"
            - name: LOCAL_FS_DIRECTORY
              value: "{{ .Values.backend.localFsDirectory }}"              
            - name: GS_BUCKET
              value: "{{ include "movetodata-gke.gsBucket" . }}"
            - name: HDFS_ENDPOINT
              value: "{{ .Values.backend.hdfsEndpoint }}"                       
            - name: MINIO_ENDPOINT
              value: "{{ .Values.backend.minioEndpoint }}"
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: token-secret
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: minio-username
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: minio-password
            - name: GOOGLE_CLOUD_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: google-cloud-credentials
          volumeMounts:
            - mountPath: "{{ .Values.backend.movetodataMountPath }}"
              name: movetodata-nfs-volume
          workingDir: "{{ .Values.backend.movetodataMountPath }}"
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      volumes:
        - name: movetodata-nfs-volume
          persistentVolumeClaim:
            claimName: movetodata-pvc

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: julia
  name: julia
  namespace: {{ .Values.namespace }}
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "movetodata-backend-config"}'
spec:
  type: NodePort
  ports:
    - name: juliaapi
      port: 58080
      targetPort: 58080
    - name: julia
      port: 58542
      targetPort: 58542
  selector:
    name: julia
status:
  loadBalancer: {}
