/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.orphea.sparkoperator.models;

import com.google.gson.annotations.SerializedName;
import io.kubernetes.client.openapi.models.V1ListMeta;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * SparkApplicationList is a list of SparkApplication
 */
@ApiModel(description = "SparkApplicationList is a list of SparkApplication")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-07T11:53:46.903Z[Etc/UTC]")
public class V1beta2SparkApplicationList implements io.kubernetes.client.common.KubernetesListObject {
    public static final String SERIALIZED_NAME_API_VERSION = "apiVersion";
    public static final String SERIALIZED_NAME_ITEMS = "items";
    public static final String SERIALIZED_NAME_KIND = "kind";
    public static final String SERIALIZED_NAME_METADATA = "metadata";
    @SerializedName(SERIALIZED_NAME_API_VERSION)
    private String apiVersion;
    @SerializedName(SERIALIZED_NAME_ITEMS)
    private List<V1beta2SparkApplication> items = new ArrayList<>();
    @SerializedName(SERIALIZED_NAME_KIND)
    private String kind;
    @SerializedName(SERIALIZED_NAME_METADATA)
    private V1ListMeta metadata = null;


    public V1beta2SparkApplicationList apiVersion(String apiVersion) {

        this.apiVersion = apiVersion;
        return this;
    }

    /**
     * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
     *
     * @return apiVersion
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources")

    public String getApiVersion() {
        return apiVersion;
    }


    public void setApiVersion(String apiVersion) {
        this.apiVersion = apiVersion;
    }


    public V1beta2SparkApplicationList items(List<V1beta2SparkApplication> items) {

        this.items = items;
        return this;
    }

    public V1beta2SparkApplicationList addItemsItem(V1beta2SparkApplication itemsItem) {
        this.items.add(itemsItem);
        return this;
    }

    /**
     * List of sparkapplications. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
     *
     * @return items
     **/
    @ApiModelProperty(required = true, value = "List of sparkapplications. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md")

    public List<V1beta2SparkApplication> getItems() {
        return items;
    }


    public void setItems(List<V1beta2SparkApplication> items) {
        this.items = items;
    }


    public V1beta2SparkApplicationList kind(String kind) {

        this.kind = kind;
        return this;
    }

    /**
     * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
     *
     * @return kind
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds")

    public String getKind() {
        return kind;
    }


    public void setKind(String kind) {
        this.kind = kind;
    }


    public V1beta2SparkApplicationList metadata(V1ListMeta metadata) {

        this.metadata = metadata;
        return this;
    }

    /**
     * Get metadata
     *
     * @return metadata
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public V1ListMeta getMetadata() {
        return metadata;
    }


    public void setMetadata(V1ListMeta metadata) {
        this.metadata = metadata;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationList v1beta2SparkApplicationList = (V1beta2SparkApplicationList) o;
        return Objects.equals(this.apiVersion, v1beta2SparkApplicationList.apiVersion) &&
                Objects.equals(this.items, v1beta2SparkApplicationList.items) &&
                Objects.equals(this.kind, v1beta2SparkApplicationList.kind) &&
                Objects.equals(this.metadata, v1beta2SparkApplicationList.metadata);
    }

    @Override
    public int hashCode() {
        return Objects.hash(apiVersion, items, kind, metadata);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta2SparkApplicationList {\n");
        sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
        sb.append("    items: ").append(toIndentedString(items)).append("\n");
        sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
        sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

