/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.orphea.sparkoperator.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * V1beta2SparkApplicationSpecSecret
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-07T11:53:46.903Z[Etc/UTC]")
public class V1beta2SparkApplicationSpecSecret {
    public static final String SERIALIZED_NAME_DEFAULT_MODE = "defaultMode";
    public static final String SERIALIZED_NAME_ITEMS = "items";
    public static final String SERIALIZED_NAME_OPTIONAL = "optional";
    public static final String SERIALIZED_NAME_SECRET_NAME = "secretName";
    @SerializedName(SERIALIZED_NAME_DEFAULT_MODE)
    private Integer defaultMode;
    @SerializedName(SERIALIZED_NAME_ITEMS)
    private List<V1beta2SparkApplicationSpecConfigMapItems> items = null;
    @SerializedName(SERIALIZED_NAME_OPTIONAL)
    private Boolean optional;
    @SerializedName(SERIALIZED_NAME_SECRET_NAME)
    private String secretName;


    public V1beta2SparkApplicationSpecSecret defaultMode(Integer defaultMode) {

        this.defaultMode = defaultMode;
        return this;
    }

    /**
     * Get defaultMode
     *
     * @return defaultMode
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Integer getDefaultMode() {
        return defaultMode;
    }


    public void setDefaultMode(Integer defaultMode) {
        this.defaultMode = defaultMode;
    }


    public V1beta2SparkApplicationSpecSecret items(List<V1beta2SparkApplicationSpecConfigMapItems> items) {

        this.items = items;
        return this;
    }

    public V1beta2SparkApplicationSpecSecret addItemsItem(V1beta2SparkApplicationSpecConfigMapItems itemsItem) {
        if (this.items == null) {
            this.items = new ArrayList<>();
        }
        this.items.add(itemsItem);
        return this;
    }

    /**
     * Get items
     *
     * @return items
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public List<V1beta2SparkApplicationSpecConfigMapItems> getItems() {
        return items;
    }


    public void setItems(List<V1beta2SparkApplicationSpecConfigMapItems> items) {
        this.items = items;
    }


    public V1beta2SparkApplicationSpecSecret optional(Boolean optional) {

        this.optional = optional;
        return this;
    }

    /**
     * Get optional
     *
     * @return optional
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getOptional() {
        return optional;
    }


    public void setOptional(Boolean optional) {
        this.optional = optional;
    }


    public V1beta2SparkApplicationSpecSecret secretName(String secretName) {

        this.secretName = secretName;
        return this;
    }

    /**
     * Get secretName
     *
     * @return secretName
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public String getSecretName() {
        return secretName;
    }


    public void setSecretName(String secretName) {
        this.secretName = secretName;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationSpecSecret v1beta2SparkApplicationSpecSecret = (V1beta2SparkApplicationSpecSecret) o;
        return Objects.equals(this.defaultMode, v1beta2SparkApplicationSpecSecret.defaultMode) &&
                Objects.equals(this.items, v1beta2SparkApplicationSpecSecret.items) &&
                Objects.equals(this.optional, v1beta2SparkApplicationSpecSecret.optional) &&
                Objects.equals(this.secretName, v1beta2SparkApplicationSpecSecret.secretName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(defaultMode, items, optional, secretName);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta2SparkApplicationSpecSecret {\n");
        sb.append("    defaultMode: ").append(toIndentedString(defaultMode)).append("\n");
        sb.append("    items: ").append(toIndentedString(items)).append("\n");
        sb.append("    optional: ").append(toIndentedString(optional)).append("\n");
        sb.append("    secretName: ").append(toIndentedString(secretName)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

