server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
    include-stacktrace: never
#  ssl:
#    key-store: classpath:springboot.p12
#    key-store-password: shalimar
#    key-store-type: pkcs12
#    key-alias: springboot
#    key-password: shalimar
  port: 58080
spring:
  banner:
    location: classpath:/banner/orphea.txt
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: admin

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 500MB
      max-request-size: 515MB


file:
  upload-dir=/Users/rakeshmalik/orphea/uploads

logging:
  level:
    org:
      springframework:
        security: DEBUG
#          web:
#            FilterChainProxy: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    supportedSubmitMethods: [ "get", "put", "post", "delete", "options", "head", "patch", "trace" ]
    doc-expansion: none
    persistAuthorization: true
    tryItOutEnabled: true
    syntaxHighlight:
      theme: arta