export const ENVOY_LIST_REQUEST = "ENVOY_LIST_REQUEST";
export const ENVOY_LIST_SUCCESS = "ENVOY_LIST_SUCCESS";
export const ENVOY_LIST_FAIL = "ENVOY_LIST_FAIL";

export const ENVOY_DELETE_REQUEST = "ENVOY_DELETE_REQUEST";
export const ENVOY_DELETE_SUCCESS = "ENVOY_DELETE_SUCCESS";
export const ENVOY_DELETE_FAIL = "ENVOY_DELETE_FAIL";

export const ENVOY_CREATE_REQUEST = "ENVOY_CREATE_REQUEST";
export const ENVOY_CREATE_SUCCESS = "ENVOY_CREATE_SUCCESS";
export const ENVOY_CREATE_FAIL = "ENVOY_CREATE_FAIL";

export const ENVOY_SOURCES_LIST_REQUEST = "ENVOY_SOURCES_LIST_REQUEST";
export const ENVOY_SOURCES_LIST_SUCCESS = "ENVOY_SOURCES_LIST_SUCCESS";
export const ENVOY_SOURCES_LIST_FAIL = "ENVOY_SOURCES_LIST_FAIL";

export const ENVOY_LINKS_LIST_REQUEST = "ENVOY_LINKS_LIST_REQUEST";
export const ENVOY_LINKS_LIST_SUCCESS = "ENVOY_LINKS_LIST_SUCCESS";
export const ENVOY_LINKS_LIST_FAIL = "ENVOY_LINKS_LIST_FAIL";
