export const CHART_FETCH_REQUEST = "CHART_FETCH_REQUEST";
export const CHART_FETCH_SUCCESS = "CHART_FETCH_SUCCESS";
export const CHART_FETCH_FAIL = "CHART_FETCH_FAIL";

export const CHART_UPDATE_REQUEST = "CHART_UPDATE_REQUEST";
export const CHART_UPDATE_SUCCESS = "CHART_UPDATE_SUCCESS";
export const CHART_UPDATE_FAIL = "CHART_UPDATE_FAIL";

export const CHART_DATASET_PANEL_REQUEST = "CHART_DATASET_PANEL_REQUEST";
export const CHART_DATASET_PANEL_SUCCESS = "CHART_DATASET_PANEL_SUCCESS";
export const CHART_DATASET_PANEL_FAIL = "CHART_DATASET_PANEL_FAIL";

