export const EDITOR_PANE_OPEN = "EDITOR_PANE_OPEN";
export const EDITOR_PANE_CLOSE = "EDITOR_PANE_CLOSE";
export const EDITOR_PANE_CHANGE = "EDITOR_PANE_CHANGE";
export const CLEAR_EDITOR_PANES = "CLEAR_EDITOR_PANES";

export const FILE_EDIT = "FILE_EDIT";
export const FILE_SAVE = "FILE_SAVE";

export const SET_BRANCH = "SET_BRANCH";
export const SET_REPOSITORY = "SET_REPOSITORY";

export const SET_FONT = "SET_FONT";
