export const LINK_LIST_REQUEST = "LINK_LIST_REQUEST";
export const LINK_LIST_SUCCESS = "LINK_LIST_SUCCESS";
export const LINK_LIST_FAIL = "LINK_LIST_FAIL";

export const LINK_DELETE_REQUEST = "LINK_DELETE_REQUEST";
export const LINK_DELETE_SUCCESS = "LINK_DELETE_SUCCESS";
export const LINK_DELETE_FAIL = "LINK_DELETE_FAIL";

export const LINK_CREATE_REQUEST = "LINK_CREATE_REQUEST";
export const LINK_CREATE_SUCCESS = "LINK_CREATE_SUCCESS";
export const LINK_CREATE_FAIL = "LINK_CREATE_FAIL";
