export const REPO_DETAILS_REQUEST = "REPO_DETAILS_REQUEST";
export const REPO_DETAILS_SUCCESS = "REPO_DETAILS_SUCCESS";
export const REPO_DETAILS_FAIL = "REPO_DETAILS_FAIL";

export const REPO_CREATE_REQUEST = "REPO_CREATE_REQUEST";
export const REPO_CREATE_SUCCESS = "REPO_CREATE_SUCCESS";
export const REPO_CREATE_FAIL = "REPO_CREATE_FAIL";

export const REPO_TREE_REQUEST = "REPO_TREE_REQUEST";
export const REPO_TREE_SUCCESS = "REPO_TREE_SUCCESS";
export const REPO_TREE_FAIL = "REPO_TREE_FAIL";

export const REPO_NODE_DATA_REQUEST = "REPO_NODE_DATA_REQUEST";
export const REPO_NODE_DATA_SUCCESS = "REPO_NODE_DATA_SUCCESS";
export const REPO_NODE_DATA_FAIL = "REPO_NODE_DATA_FAIL";
