-- not used
--alter table if exists kitab_branches add constraint UKt81muuluj7iim130pop99v7vc unique (dataset_id, branch);
--
--alter table if exists kitab_dataset add constraint UKf5uen81vxj6aq0q3jjwyobpvw unique (id, branch);
--alter table if exists kitab_transactions add constraint UKeq89jx1em7e06r5ejseepcxef unique (dataset_id, branch);
--alter table if exists passport_groups_groups_administrators add constraint UK_31kmbg9f8eo3cw9c378wkf0hv unique (groups_administrators_id);
--alter table if exists passport_groups_groups_members add constraint UK_8ycesu1nwlkrpsoq867cbwxe9 unique (groups_members_id);
--alter table if exists passport_groups_groups_owners add constraint UK_gfbn4rt2jkvir1a61fa1m7gju unique (groups_owners_id);
--alter table if exists passport_role_permissions add constraint UK_26ui4yr8bnlaeb355vxnfiv2c unique (permissions_id);
--alter table if exists charts_model_filters add constraint FK3h2vekbou0jt9ck2vhobv2cca foreign key (charts_model_id) references kepler_charts;
--alter table if exists charts_model_x_axis add constraint FK53v7s8v2xr0cvx7fatg56jbme foreign key (charts_model_id) references kepler_charts;
--alter table if exists charts_model_y_axis add constraint FK7ijcyp5j83exv2ast7eblltjp foreign key (charts_model_id) references kepler_charts;
--alter table if exists dashboards_model_elements add constraint FKho8j99ca1ct89b3qlrvy27go6 foreign key (dashboards_model_id) references kepler_dashboards;
--alter table if exists passport_groups_groups_administrators add constraint FK28fstxhuat5qct7797019rvtf foreign key (groups_administrators_id) references passport_users;
--alter table if exists passport_groups_groups_administrators add constraint FKq0v9stswor445r7uwp1oylg1o foreign key (groups_id) references passport_groups;
--alter table if exists passport_groups_groups_members add constraint FKkbjmfxnmjlw4kj7bihu5aj48r foreign key (groups_members_id) references passport_users;
--alter table if exists passport_groups_groups_members add constraint FKpfshsqiddpvr893aoqdr1v07j foreign key (groups_id) references passport_groups;
--alter table if exists passport_groups_groups_owners add constraint FK3pqsvl8rwslhn2cipcviay52l foreign key (groups_owners_id) references passport_users;
--alter table if exists passport_groups_groups_owners add constraint FKn3exhhb9audaf5ic13a3xuxqy foreign key (groups_id) references passport_groups;
--alter table if exists passport_role_permissions add constraint FKiokt7obw7rthda2ikur3v7h58 foreign key (permissions_id) references passport_permissions;
--alter table if exists passport_role_permissions add constraint FK9yl9n46dj9ak3j3jmdyg5nphx foreign key (role_id) references passport_role;
--alter table if exists postgres_sync_specification_index_names add constraint FKqpd6hc4mlvigf7gb6gcaepo76 foreign key (postgres_sync_specification_id) references synchro_postgres_sync_specifications;
--alter table if exists sources_agent_id add constraint FKs7j9fxlg4eq29kpch6m3o98w6 foreign key (sources_id) references ignite_agent_sources;