apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: frontend
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
        - image: "{{ include "bosler-aks.repo_path" . }}frontend:{{ .Values.versions.frontend }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          name: frontend
          ports:
            - containerPort: 80
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: frontend
  name: frontend
  namespace: {{ .Values.namespace }}
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "bosler-backend-config"}'
spec:
  type: NodePort
  ports:
    - name: frontend
      port: 80
      targetPort: 80
  selector:
    name: frontend
status:
  loadBalancer: {}
