/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.movetodata.sparkoperator.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1beta2SparkApplicationSpecAzureFile
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-11-07T11:53:46.903Z[Etc/UTC]")
public class V1beta2SparkApplicationSpecAzureFile {
    public static final String SERIALIZED_NAME_READ_ONLY = "readOnly";
    public static final String SERIALIZED_NAME_SECRET_NAME = "secretName";
    public static final String SERIALIZED_NAME_SHARE_NAME = "shareName";
    @SerializedName(SERIALIZED_NAME_READ_ONLY)
    private Boolean readOnly;
    @SerializedName(SERIALIZED_NAME_SECRET_NAME)
    private String secretName;
    @SerializedName(SERIALIZED_NAME_SHARE_NAME)
    private String shareName;


    public V1beta2SparkApplicationSpecAzureFile readOnly(Boolean readOnly) {

        this.readOnly = readOnly;
        return this;
    }

    /**
     * Get readOnly
     *
     * @return readOnly
     **/
    @javax.annotation.Nullable
    @ApiModelProperty(value = "")

    public Boolean getReadOnly() {
        return readOnly;
    }


    public void setReadOnly(Boolean readOnly) {
        this.readOnly = readOnly;
    }


    public V1beta2SparkApplicationSpecAzureFile secretName(String secretName) {

        this.secretName = secretName;
        return this;
    }

    /**
     * Get secretName
     *
     * @return secretName
     **/
    @ApiModelProperty(required = true, value = "")

    public String getSecretName() {
        return secretName;
    }


    public void setSecretName(String secretName) {
        this.secretName = secretName;
    }


    public V1beta2SparkApplicationSpecAzureFile shareName(String shareName) {

        this.shareName = shareName;
        return this;
    }

    /**
     * Get shareName
     *
     * @return shareName
     **/
    @ApiModelProperty(required = true, value = "")

    public String getShareName() {
        return shareName;
    }


    public void setShareName(String shareName) {
        this.shareName = shareName;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V1beta2SparkApplicationSpecAzureFile v1beta2SparkApplicationSpecAzureFile = (V1beta2SparkApplicationSpecAzureFile) o;
        return Objects.equals(this.readOnly, v1beta2SparkApplicationSpecAzureFile.readOnly) &&
                Objects.equals(this.secretName, v1beta2SparkApplicationSpecAzureFile.secretName) &&
                Objects.equals(this.shareName, v1beta2SparkApplicationSpecAzureFile.shareName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(readOnly, secretName, shareName);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class V1beta2SparkApplicationSpecAzureFile {\n");
        sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
        sb.append("    secretName: ").append(toIndentedString(secretName)).append("\n");
        sb.append("    shareName: ").append(toIndentedString(shareName)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

