apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: database
  name: boson-db
  namespace: "{{ .Values.namespace }}"
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  selector:
    matchLabels:
      service: boson-db
  template:
    metadata:
      labels:
        service: boson-db
    spec:
      containers:
        - name: boson-db
          image: postgres:11-alpine
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: boson-db-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: boson-db-password
          # volumeMounts:
          #   - mountPath: /var/lib/postgresql/data
          #     name: movetodata-nfs-volume
          #     subPath: postgres
          volumeMounts:
            # - mountPath: "{{ .Values.backend.movetodataMountPath }}"
            #   name: movetodata-nfs-volume
            - mountPath: /var/lib/postgresql/data
              name: movetodata-local-fs
              subPath: postgres

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        # - name: movetodata-nfs-volume
        #   persistentVolumeClaim:
        #     claimName: movetodata-pvc
        - name: movetodata-local-fs
          hostPath:
            path: "{{ .Values.backend.movetodataMountPath }}"
---
apiVersion: v1
kind: Service
metadata:
  name: boson-db
  namespace: "{{ .Values.namespace }}"
  labels:
    service: boson-db
spec:
  selector:
    service: boson-db
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
