apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: callisto
  name: callisto
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: callisto
  template:
    metadata:
      labels:
        name: callisto
    spec:
      containers:
        - image: "{{ include "movetodata-gke.repo_path" . }}callisto:{{ .Values.versions.callisto }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          name: callisto
          ports:
            - containerPort: 8686
          env:
            - name: BASE_URL
              value: "{{ include "movetodata-gke.baseUrl" . }}"
            - name: MOVETODATA_API
              value: "http://{{ .Values.backend.host }}:8080"
            - name: BUILD_TYPE
              value: "PREVIEW"              
            - name: BUILD_TOKEN
              value: "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI4NWMzYjA1MS05ODUwLTRhOGMtYjkzNi0xNGZmZGZkMWRiMzQiLCJpYXQiOjE2ODU2MDUyMzIsImV4cCI6MTY5NTM0MDgwMH0.PrMmOj-YV0t9w6nJxa9ADR1Qqh6LedE8KX8EyvoWc0gs2KYqGhvCVjScaPmXvBRUzsyimfQAxC1GDtvkhVnZvA"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: boson-db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: boson-db-password
            - name: DB_HOST
              value: "{{ .Values.backend.dbHost }}"
            - name: DB_PORT
              value: "{{ .Values.backend.dbPort }}"
            - name: HOST
              value: "{{ .Values.backend.host }}"
            - name: JULIA_HOST
              value: "{{ .Values.julia.host }}"              
            - name: JULIA_API_PORT
              value: "{{ .Values.julia.apiPort }}"
            - name: JULIA_PORT
              value: "{{ .Values.julia.gitPort }}"
            - name: GIT_CLONED_PATH
              value: "{{ .Values.backend.movetodataMountPath }}/git/cloned"
            - name: BACKING_FS
              value: "{{ .Values.backend.backingFs }}"
            - name: LOCAL_FS_DIRECTORY
              value: "{{ .Values.backend.localFsDirectory }}"              
            - name: HDFS_ENDPOINT
              value: "{{ .Values.backend.hdfsEndpoint }}"              
            - name: GS_BUCKET
              value: "{{ include "movetodata-gke.gsBucket" . }}"
            - name: MINIO_ENDPOINT
              value: "{{ .Values.backend.minioEndpoint }}"
            - name: NOTEBOOK_DIR
              value: "{{ .Values.backend.movetodataMountPath }}/git/cloned/"
            - name: NOTEBOOK_TOKEN
              value: "{{ .Values.backend.notebookToken }}"
            - name: FRACTAL_TEMPLATES_PATH
              value: "/app/FractalTemplates"        
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: token-secret
            - name: FRACTAL_TEMPLATES_TOKEN
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: fractal-templates-token
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: minio-username
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: minio-password
            - name: GOOGLE_CLOUD_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: movetodata-secret
                  key: google-cloud-credentials
                  
          volumeMounts:
            # - mountPath: "{{ .Values.backend.movetodataMountPath }}"
            #   name: movetodata-nfs-volume
            - mountPath: "{{ .Values.backend.movetodataMountPath }}"
              name: movetodata-local-fs
          workingDir: "{{ .Values.backend.movetodataMountPath }}"
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      volumes:
        # - name: movetodata-nfs-volume
        #   persistentVolumeClaim:
        #     claimName: movetodata-pvc
        - name: movetodata-local-fs
          hostPath:
            path: "{{ .Values.backend.movetodataMountPath }}"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: callisto
  name: callisto
  namespace: {{ .Values.namespace }}
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "movetodata-backend-config"}'
spec:
  type: NodePort
  ports:
    - name: callisto
      port: 8686
      targetPort: 8686
  selector:
    name: callisto
status:
  loadBalancer: {}
