apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data:
  # values are base64 encoded, which obscures them but does NOT provide
  # any useful level of confidentiality
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZaVENDQkUyZ0F3SUJBZ0lTQTBMNjF0NDda
    ZEdUT0FncnkrYkhjYUpWTUEwR0NTcUdTSWIzRFFFQkN3VUEKTURNeEN6QUpCZ05WQkFZVEFsVlRN
    Ull3RkFZRFZRUUtFdzFNWlhRbmN5QkZibU55ZVhCME1Rd3dDZ1lEVlFRRApFd05TTVRFd0hoY05N
    alF3TnpFM01URXdOREExV2hjTk1qUXhNREUxTVRFd05EQTBXakFZTVJZd0ZBWURWUVFECkV3MWta
    WFl1WW05emJHVnlMbWx2TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FR
    RUEKdDZZYnZsMTFoTG1US2RLS21EUFVUQVlpalJ1WFFSZ3BPMHZsNHBqZGtmNDluZ0Znb3FZWDZZ
    QXR6VE1pWU9weApNWXd3L21aeDVPZ3krUCtMbks2V3FMOVY3MUUvMFUycGo5SWlKaHlYTjdpY3JV
    N1FHTE5JLy9hNUNlL2hJNFJuCk9mNDY1ck03OFBpOE5sWDhUdldLU2d4R0gvUWdpbzFMZktPY3U3
    a3lxN0N0TkhLUkRLNms5UkNxa3hVRjFjMXkKNjFtdCtaRUZqWXpMTUs0WHNGazNod3oyUmJHeGZo
    Y1hmM0V3eFdtSWhGZUVPV0V6QzZsMHNYRmVHVkhCM1FCSgozZ0YxVnRacmZSK1owSEo4SkdEY0ZE
    L2c3ZHdsVnpUaEExSmsxNzltcUpWQThlb0U0bjUrOEk2a1VhSFk4aHphCm4vb3hWWDZ6Vzd5MUZl
    bzFSOVp3WndJREFRQUJvNElDakRDQ0FvZ3dEZ1lEVlIwUEFRSC9CQVFEQWdXZ01CMEcKQTFVZEpR
    UVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFV
    ZApEZ1FXQkJTRUlKQ2duZXorWTdLUStBSHBTT0hqbU5zeEN6QWZCZ05WSFNNRUdEQVdnQlRGejBh
    azZ2VER3SHBzCmxjUXRzRjZTTHlianVUQlhCZ2dyQmdFRkJRY0JBUVJMTUVrd0lnWUlLd1lCQlFV
    SE1BR0dGbWgwZEhBNkx5OXkKTVRFdWJ5NXNaVzVqY2k1dmNtY3dJd1lJS3dZQkJRVUhNQUtHRjJo
    MGRIQTZMeTl5TVRFdWFTNXNaVzVqY2k1dgpjbWN2TUlHUkJnTlZIUkVFZ1lrd2dZYUNFR0YxY205
    eVlTNWliM05zWlhJdWFXK0NEbUp2Y21FdVltOXpiR1Z5CkxtbHZnZzlpZFhKaGJpNWliM05zWlhJ
    dWFXK0NEbVJsYlc4dVltOXpiR1Z5TG1sdmdnMWtaWFl1WW05emJHVnkKTG1sdmdnOXVaWGgxY3k1
    aWIzTnNaWEl1YVcrQ0RuTnVZWEF1WW05emJHVnlMbWx2Z2hGemRHRm5hVzVuTG1KdgpjMnhsY2k1
    cGJ6QVRCZ05WSFNBRUREQUtNQWdHQm1lQkRBRUNBVENDQVFVR0Npc0dBUVFCMW5rQ0JBSUVnZllF
    CmdmTUE4UUIyQUhiL2lEOEt0dnVWVWNKaHpQV0h1alMwcE0yN0tkeG9RZ3FmNW1kTVdqcDBBQUFC
    a01DVUNhd0EKQUFRREFFY3dSUUlnQittblQwZnREeC9oWTJqbXZJRkNqeWNOcEpXYmM1R0prdEgz
    ckpmbFdPMENJUUNJTysrVQpBZUp0N1NvRUc3MTNwMTlxRG9LdnVCdDdCeFZ4blpzU2RVbjdad0Iz
    QU4vaFZ1dXFCYSsxbkErR2NZMm93REpPCnJsYlpicWYxcFdvQjBjRTd2bEpjQUFBQmtNQ1VDa2NB
    QUFRREFFZ3dSZ0loQUo5blpBYWlWSDNsNk1uTzV3alAKTit0UGlyRGxwTkxOQm5jekdoM29XeGE1
    QWlFQXYyc2tQRW4zRzFtVUVUYzBabDltZ1dtY3lmbDJRN0tRNjNIego1Mk5rSDY0d0RRWUpLb1pJ
    aHZjTkFRRUxCUUFEZ2dFQkFCN05QeGIrakJlNWJkSldEdWtKcmFUb3ZabzIzY2JGCnhtVnNjdTlx
    Wi9rOWpqWlVOeHhpL2x5U215WW9jNFdUSUdQQjJHTFJlQkVUWXlVT21MZjFVN3MyS0plcWZ1UFAK
    T0YwZ2ZkeEUvU2wvS2t5SFRGNFJiZFcrNVI5Q040cG9qYlpadjNkd0V4SS9kZUtraHZsS1plem1B
    bHlERWs2bwp3UGllaXMzN25NeVI2YkpqUVhPZmFjSlBLY25VMm9GbHpkRHR4NXByVzBmNWJSZzJO
    Zy9HbS9ISFBQTFRxd3hBCmRnNXExcTZOUXA5dzNEaVVlYUZ0VTRVN0c2V3Zhc1ZRZ0RWalZEZyto
    TXkrc3lmb20rM2cyWTNuSmxTWjF0U3QKR2JibUUyZDhrZEZyWWY5WUo2Z2FYMkV1WFE5SWp5ZGxQ
    aGRqbVpOUWJWK2loaG5RYkdHZGMzcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJF
    R0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRkJqQ0NBdTZnQXdJQkFnSVJBSXA5UGhQV0x6RHZJNGE5
    S1Fkck5QZ3dEUVlKS29aSWh2Y05BUUVMQlFBdwpUekVMTUFrR0ExVUVCaE1DVlZNeEtUQW5CZ05W
    QkFvVElFbHVkR1Z5Ym1WMElGTmxZM1Z5YVhSNUlGSmxjMlZoCmNtTm9JRWR5YjNWd01SVXdFd1lE
    VlFRREV3eEpVMUpISUZKdmIzUWdXREV3SGhjTk1qUXdNekV6TURBd01EQXcKV2hjTk1qY3dNekV5
    TWpNMU9UVTVXakF6TVFzd0NRWURWUVFHRXdKVlV6RVdNQlFHQTFVRUNoTU5UR1YwSjNNZwpSVzVq
    Y25sd2RERU1NQW9HQTFVRUF4TURVakV4TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFN
    SUlCCkNnS0NBUUVBdW9lOFhCc0FPY3ZLQ3MzVVp4RDVBVHlsVHFWaHl5YktVdnNWQWJlNUtQVW9I
    dTBuc3lRWU9XY0oKREFqczREcXdPM2NPdmZQbE9WUkJERTZ1UWRhWmRONVIyKzk3LzFpOXFMY1Q5
    dDR4MWZKeXlYSnFDNE4wbFp4RwpBR1FVbWZPeDJTTFp6YWlTcWh3bWVqLys3MWdGZXdpVmdkdHhE
    NDc3NHpFSnV3bStVRTFmajVGMlBWcWRub1B5CjZjUm1zK0VHWmtOSUdJQmxvRGNZbXB1RU1wZXhz
    cjNFK0JVQW5TZUkrK0pqRjVac215ZG5TOFRiS0Y1cHdubncKU1Z6Z0pGRGh4THloQmF4N1FHMEF0
    TUpCUDZkWXVDL0ZYSnVsdXdtZThmN3JzSVU1L2FnSzcwWEVlT3RsS3NMUApYenplNDF4TkcvY0xK
    eXVxQzBKM1UwOTVhaDJIMlFJREFRQUJvNEg0TUlIMU1BNEdBMVVkRHdFQi93UUVBd0lCCmhqQWRC
    Z05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBZ1lJS3dZQkJRVUhBd0V3RWdZRFZSMFRBUUgvQkFnd0Jn
    RUIKL3dJQkFEQWRCZ05WSFE0RUZnUVV4YzlHcE9yMHc4QjZiSlhFTGJCZWtpOG00N2t3SHdZRFZS
    MGpCQmd3Rm9BVQplYlJaNW51MjVlUUJjNEFJaU1nYVdQYnBtMjR3TWdZSUt3WUJCUVVIQVFFRUpq
    QWtNQ0lHQ0NzR0FRVUZCekFDCmhoWm9kSFJ3T2k4dmVERXVhUzVzWlc1amNpNXZjbWN2TUJNR0Ex
    VWRJQVFNTUFvd0NBWUdaNEVNQVFJQk1DY0cKQTFVZEh3UWdNQjR3SEtBYW9CaUdGbWgwZEhBNkx5
    OTRNUzVqTG14bGJtTnlMbTl5Wnk4d0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnSUJBRTdpaVYwS0F4
    eVFPTkQxSC9seFhQakRqN0kzaUhwdnNDVWY3YjYzMklZR2p1a0poTTF5CnY0SHovTXJQVTBqdHZm
    WnBRdFNsRVQ0MXlCT3lraDBGWCtvdTFOajRTY090OVptV25POG0yT0cwSkF0SUlFMzgKMDFTMHFj
    WWh5T0UyRy85M1pDa1h1ZkJMNzEzcXpYblF2NUMvdmlPeWtOcEtxVWd4ZEtsRUMrSGk5aTJEY2FS
    MQplOUtVd1FVWlJoeTVqL1BFZEVnbEtnM2w5ZHRENHR1VG03a1p0Qjh2MzJvT2p6SFRZdys3S2R6
    ZFppdy9zQnRuClVmaEJQT1JOdWF5NHBKeG1ZL1dyaFNNZHpGTzJxM0d1M01VQmNkbzI3Z29ZS2pM
    OUNURjhqL1p6NTV5Y3RVb1YKYW5lQ1dzL2FqVVgrSHlwa0JUQStjOExHRExuV08yTktxMFlEL3Bu
    QVJrQW5ZR1BmVURvSFI5Z1ZTcC9xUngrWgpXZ2hpRExac013aE4xemp0U0MwdUJXaXVnRjN2VE56
    WUlFRmZhUEc3V3MzakRyQU1NWWViUTk1SlErSElCRC9SClBCdUhSVEJwcUtseURua1NIREhZUGlO
    WDNhZFBvUEFjZ2RGM0gyL1cwcm1vc3dNV2dUbExuMVd1MG1ya3M3L3EKcGRXZlM2UEoxanR5ODBy
    MlZLc00vRGozWUlEZmJqWEtkYUZVNUMrOGJoZkpHcVUzdGFLYXV1ejB3SFZHVDNlbwo2RmxXa1dZ
    dGJ0NHBnZGFtbHdWZVpFVytMTTdxWkVKRXNNTlByZkMwM0FQS21ac0pncFdDRFdPS1p2a1pjdmpW
    CnVZa1E0b21ZQ1RYNW9oeStrbk1qZE9tZEg5YzdTcHFFV0JEQzg2ZmlOZXgrTzBYT01FWlNhOERB
    Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K


  # In this example, the key data is not a real PEM-encoded private key
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktnd2dnU2tBZ0VBQW9JQkFRQzNwaHUrWFhXRXVaTXAKMG9xWU05Uk1CaUtORzVkQkdDazdT
    K1hpbU4yUi9qMmVBV0NpcGhmcGdDM05NeUpnNm5FeGpERCtabkhrNkRMNAovNHVjcnBhb3YxWHZV
    VC9SVGFtUDBpSW1ISmMzdUp5dFR0QVlzMGovOXJrSjcrRWpoR2M1L2pybXN6dncrTHcyClZmeE85
    WXBLREVZZjlDQ0tqVXQ4bzV5N3VUS3JzSzAwY3BFTXJxVDFFS3FURlFYVnpYTHJXYTM1a1FXTmpN
    c3cKcmhld1dUZUhEUFpGc2JGK0Z4ZC9jVERGYVlpRVY0UTVZVE1McVhTeGNWNFpVY0hkQUVuZUFY
    VlcxbXQ5SDVuUQpjbndrWU53VVArRHQzQ1ZYTk9FRFVtVFh2MmFvbFVEeDZnVGlmbjd3anFSUm9k
    anlITnFmK2pGVmZyTmJ2TFVWCjZqVkgxbkJuQWdNQkFBRUNnZ0VBTlh4a1VpSUlDdnE5T0k0QUhX
    bmk1NjFWdk1FUFlUNzNLelRrcEFVZmF0aWYKKzNldFBGR2hYemtjbmNuSnRtNHhQMXYwSFBPYk1p
    N0tRYWl6Y1pPTGYyUVNWQnZXdVUra0ZhWCttaGp6bFovbgp5YlhOZDVRbnE1eWdzWnN5ZDlTazk4
    ZnFRYXhyeGJlN29SdVQyeTg1OG16MnMzRzNWSUxvUEVtdWFTSDc5dktFCllyWCt5bTQ3SmZJSGg3
    SFIyWGczNXcrRStpUEY3eC84ZjRTVU1senIwY25lMS82YlQ1cFRkNVlYNjdYK3diYVoKSEhkc0tJ
    SDd0TnNtb0VsVnpZN3Y1RzJKTTZMcnNIbmRwMzNiRm9RSGlweE9hNXF4NjNRSk0weUozR0lXMUYx
    bApzZ0kyZ2FXZ2htR0xCaVRFVXVDZHdjelhCSkNsc3hZNFJKRjI3clZkNFFLQmdRRGlzTWRpZlph
    cjl4T29MTjFrClZhS3hYUWpTVHhMYS9QZ3VjenBCNmJGNEpMbGZRaFVyc0tZdUFKWnFUSzFiaGd1
    ZE9DcG5FVXNPSVpoTmxMdGsKcVdudk1yTVRHVHBGV2lDSjdQT3dPUGRoaTUzdU1ZTkg3b1pPUDZ2
    ZEZNZXc2K0NOVkJaM25BbGtuWktSTEZSUwpJNWF1ZzgvVVZKamorM0dKK0s4ZmIyaVVGd0tCZ1FE
    UFpMSFQzM1d0S0NRRThCcXFuZnRJK2RLc3lBRFFiNGlqCjRjeDNtSWRsRG14cnd1ZVMyWTZsYW9B
    cktRQVArUjFXV2tBK2VyL0ZWYzB3TGEwbWV4cmpZQ05aUjJtbHZGaEQKN0doWm5YK2lqQjh4Q1hQ
    bG9PNy9RR282QXYrYlhNNGFpVzF6WkRROUlQOElrVkNOTHExdlZ4UGNKWG82Q0xuYQo2V0h2R0ZX
    b01RS0JnUUMwRTlRL3RCNWwrdjlkZ0U1YXJ3QnZ2c1VNTkE1NWNhMUJVUDI5Y0lRdk9aVWNTK1Yv
    CmNIT0NaYXNYUkZRT09YeXVadmlnS1llaThTTUl0aGJxenYyOUsxdy8xckdJZUNFVEQrMUJWdStG
    U0tDcm9COTIKbTgrTEIxOWlYMmlHYmNwUzJyS0NUNnpTaGEzeHJ2SkkwY2FZV1ZOV2krRnNjY2p1
    M21OWEtHdzkvd0tCZ1FDaAorNERVL2Z5WVVQakpEb3VWWlN6bUU1SFR0NmJESmNud1RpVDM2Qjhm
    OUFNRXE4ZFpNQ2swMDVqbG5QRmFpSFM4CmhHTVhLYUpzeTVZbW9oWlNMdWFTWHYxYzl1VHlPTWdy
    elJLM284Y1R1eU9GbGw5Nkk1ZG5yL1VIK0YyU0NBdEcKT0w1TzJSM2YvTXlVOFlLYnNyQnRmUEti
    Q0g2Tm8xRWVSUmhqdVhyMWtRS0JnQ3hNcGI2ZFZuaHlvRWEwTkp2SApMZGRZZDBicU5qbzZkNEN5
    TjBNMnVIZHZ2SHlPRnNTeFRnYW5qMEdZOTdXcHBBd1hBQWsvbFFlQVpRS0hjcFluCmFxTFAzQndE
    a29SdDFlTVdPOUhHTXlDZkxSNldQYjlxRGFsMmRRKzRCOUNYQmZhbk5vNHRPYTJSWjVCSFVnZ0IK
    QS9aSFlmc2R3QWFGMWFvbjRwa3BpS0RmCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
